const {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const {query}=require('../../services/db');
const {CustomIds}=require('../ui/customIds');
const {createBaseEmbed,SlickBotColors}=require('../ui/uiService');
const {truncate}=require('../../utils/format');
const parse=(v,f)=>{if(!v)return f;if(typeof v==='object')return v;try{return JSON.parse(v)}catch{return f}};
const json=v=>v?JSON.stringify(v):null;
const next=(table,col)=>`SELECT COALESCE(MAX(${col}),0)+1 AS next_number FROM ${table} WHERE guild_id=$1`;
async function sendable(client,id){if(!id)return null;const c=await client.channels.fetch(id).catch(()=>null);return c?.isTextBased?.()&&typeof c.send==='function'?c:null}
async function teamRoles(id){if(!id)return[];return(await query('SELECT role_id FROM permission_team_roles WHERE team_id=$1',[id]).catch(()=>({rows:[]}))).rows.map(r=>r.role_id)}
async function teamId(guildId,name){if(!name)return null;return(await query('SELECT id FROM permission_teams WHERE guild_id=$1 AND LOWER(name)=LOWER($2) LIMIT 1',[guildId,name]).catch(()=>({rows:[]}))).rows[0]?.id||null}
const answerText=a=>{const e=Object.entries(parse(a,{}));return e.length?e.map(([q,v])=>`**${q}**\n${truncate(String(v||'No answer provided.'),700)}`).join('\n\n'):'No answers provided.'};

class TicketService{
 async getConfig(g){let r=await query('SELECT * FROM ticket_configs WHERE guild_id=$1 LIMIT 1',[g]);if(r.rows[0])return r.rows[0];return(await query('INSERT INTO ticket_configs (guild_id) VALUES ($1) ON CONFLICT (guild_id) DO UPDATE SET updated_at=NOW() RETURNING *',[g])).rows[0]}
 async listTypes(g){await this.ensureDefaultType(g);return(await query('SELECT * FROM ticket_types WHERE guild_id=$1 ORDER BY name',[g])).rows}
 async getTypeById(g,id){return(await query('SELECT * FROM ticket_types WHERE guild_id=$1 AND id=$2 LIMIT 1',[g,id])).rows[0]||null}
 async getTypeByName(g,n){return(await query('SELECT * FROM ticket_types WHERE guild_id=$1 AND LOWER(name)=LOWER($2) LIMIT 1',[g,n])).rows[0]||null}
 async addQuestion(g,n,q,required=true){const t=await this.getTypeByName(g,n);if(!t)return null;const qs=parse(t.questions,[]);qs.push({label:q,required});return(await query('UPDATE ticket_types SET questions=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[json(qs.slice(0,4)),t.id])).rows[0]}
 async clearQuestions(g,n){const t=await this.getTypeByName(g,n);if(!t)return null;return(await query("UPDATE ticket_types SET questions='[]'::jsonb,updated_at=NOW() WHERE id=$1 RETURNING *",[t.id])).rows[0]}
 async deleteType(g,n){const t=await this.getTypeByName(g,n);if(!t)return{ok:false,reason:'Ticket type not found.'};const c=await query("SELECT COUNT(*)::int AS count FROM tickets WHERE guild_id=$1 AND ticket_type_id=$2 AND status='OPEN'",[g,t.id]);if(c.rows[0]?.count)return{ok:false,reason:'This ticket type still has open tickets. Close them first.'};await query('DELETE FROM ticket_types WHERE guild_id=$1 AND id=$2',[g,t.id]);return{ok:true,type:t}}
 async findOpenTicketByChannel(g,c){return(await query("SELECT * FROM tickets WHERE guild_id=$1 AND channel_id=$2 AND status='OPEN' LIMIT 1",[g,c])).rows[0]||null}
 async claimTicket({interaction,logger}){const t=await this.findOpenTicketByChannel(interaction.guildId,interaction.channelId);if(!t)return{ok:false,reason:'This channel is not an open SlickBot ticket.'};const u=(await query('UPDATE tickets SET claimed_by_user_id=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[interaction.user.id,t.id])).rows[0];await logger.log({guildId:interaction.guildId,eventKey:'ticket-claim',title:'Ticket Claimed',body:`Ticket #${t.ticket_number} claimed by ${interaction.user.tag}.`,actorUserId:interaction.user.id}).catch(()=>{});return{ok:true,ticket:u}}
 async setPriority({interaction,logger,priority}){const t=await this.findOpenTicketByChannel(interaction.guildId,interaction.channelId);if(!t)return{ok:false,reason:'This channel is not an open SlickBot ticket.'};const u=(await query('UPDATE tickets SET priority=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[priority,t.id])).rows[0];await logger.log({guildId:interaction.guildId,eventKey:'ticket-priority',title:'Ticket Priority Updated',body:`Ticket #${t.ticket_number} priority changed to **${priority}**.`,actorUserId:interaction.user.id}).catch(()=>{});return{ok:true,ticket:u}}
 async closeTicket({interaction,client,logger,reason='No reason provided.'}){const t=await this.findOpenTicketByChannel(interaction.guildId,interaction.channelId);if(!t)return{ok:false,reason:'This channel is not an open SlickBot ticket.'};const cfg=await this.getConfig(interaction.guildId),type=t.ticket_type_id?await this.getTypeById(interaction.guildId,t.ticket_type_id):null;let transcriptSent=false;const log=await sendable(client,type?.log_channel_id||cfg.log_channel_id);if(log&&(type?.transcript_enabled??cfg.transcript_enabled)!==false){const txt=await this.buildTranscript(interaction.channel,t,reason,interaction.user);await log.send({embeds:[createBaseEmbed({title:`Ticket #${t.ticket_number} Transcript`,description:`Closed By: <@${interaction.user.id}>\nReason: ${reason}`,color:SlickBotColors.INFO})],files:[new AttachmentBuilder(Buffer.from(txt),{name:`ticket-${t.ticket_number}-transcript.txt`})]});transcriptSent=true}const u=(await query("UPDATE tickets SET status='CLOSED',closed_by_user_id=$1,closed_at=NOW(),close_reason=$2,transcript_sent=$3,updated_at=NOW() WHERE id=$4 RETURNING *",[interaction.user.id,reason,transcriptSent,t.id])).rows[0];await interaction.channel.permissionOverwrites.edit(t.opener_user_id,{SendMessages:false}).catch(()=>{});await interaction.channel.setName(`closed-${interaction.channel.name}`.slice(0,95)).catch(()=>{});await logger.log({guildId:interaction.guildId,eventKey:'ticket-close',title:'Ticket Closed',body:`Ticket #${t.ticket_number} closed.`,actorUserId:interaction.user.id}).catch(()=>{});return{ok:true,ticket:u,transcriptSent,shouldDelete:transcriptSent,deleteSeconds:Number(cfg.close_delete_seconds||10)}}
 async buildTranscript(ch,t,reason,by){const ms=[];let before;while(ms.length<1000){const f=await ch.messages.fetch({limit:100,before}).catch(()=>null);if(!f?.size)break;ms.push(...f.values());before=f.last().id;if(f.size<100)break}const lines=['SlickBot Ticket Transcript',`Ticket: #${t.ticket_number}`,`Closed By: ${by.tag}`,`Reason: ${reason}`,''];for(const m of ms.reverse())lines.push(`[${m.createdAt?.toISOString()}] ${m.author?.tag||'Unknown'}\n${m.content||'[No text content]'}`);return lines.join('\n\n')}
}

class ReportService{
 async getConfig(g){return(await query('SELECT * FROM report_configs WHERE guild_id=$1 LIMIT 1',[g])).rows[0]||null}
 async updateConfig(g,i){const tid=await teamId(g,i.pingTeamName);return(await query(`INSERT INTO report_configs (guild_id,review_channel_id,ping_role_id,ping_team_id,panel_title,panel_description,panel_color,panel_display_mode) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (guild_id) DO UPDATE SET review_channel_id=COALESCE(EXCLUDED.review_channel_id,report_configs.review_channel_id),ping_role_id=COALESCE(EXCLUDED.ping_role_id,report_configs.ping_role_id),ping_team_id=COALESCE(EXCLUDED.ping_team_id,report_configs.ping_team_id),panel_title=COALESCE(EXCLUDED.panel_title,report_configs.panel_title),panel_description=COALESCE(EXCLUDED.panel_description,report_configs.panel_description),panel_color=COALESCE(EXCLUDED.panel_color,report_configs.panel_color),panel_display_mode=COALESCE(EXCLUDED.panel_display_mode,report_configs.panel_display_mode),updated_at=NOW() RETURNING *`,[g,i.reviewChannelId||null,i.pingRoleId||null,tid,i.panelTitle||null,i.panelDescription||null,i.panelColor||null,i.panelDisplayMode||null])).rows[0]}
 async getReviewerRoleIds(g){const c=await this.getConfig(g);return c?[...new Set([c.ping_role_id,...await teamRoles(c.ping_team_id)].filter(Boolean))]:[]}
 async createReport({interaction,client,logger,type='General Report',targetUser=null,details,messageLink=null}){const n=Number((await query(next('reports','report_number'),[interaction.guildId])).rows[0].next_number);const r=(await query("INSERT INTO reports (guild_id,report_number,reporter_user_id,reporter_user_tag,target_user_id,target_user_tag,report_type,message_link,details,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'OPEN') RETURNING *",[interaction.guildId,n,interaction.user.id,interaction.user.tag,targetUser?.id||null,targetUser?.tag||null,type,messageLink,details])).rows[0];const c=await sendable(client,(await this.getConfig(interaction.guildId))?.review_channel_id);if(c){const msg=await c.send({content:(await this.getReviewerRoleIds(interaction.guildId)).map(x=>`<@&${x}>`).join(' ')||undefined,...buildReportReviewPayload(r)});await query('UPDATE reports SET review_channel_id=$1,review_message_id=$2 WHERE id=$3',[c.id,msg.id,r.id]);r.review_channel_id=c.id;r.review_message_id=msg.id}await logger.log({guildId:interaction.guildId,eventKey:'report-submit',title:'Report Submitted',body:`Report #${n} submitted.`,actorUserId:interaction.user.id}).catch(()=>{});return r}
 async getReport(g,id){return(await query('SELECT * FROM reports WHERE guild_id=$1 AND id=$2 LIMIT 1',[g,id])).rows[0]||null}
 async claimReport({guildId,reportId,reviewer,logger}){const r=(await query("UPDATE reports SET status='CLAIMED',claimed_by_user_id=$1,updated_at=NOW() WHERE guild_id=$2 AND id=$3 AND status IN ('OPEN','CLAIMED') RETURNING *",[reviewer.id,guildId,reportId])).rows[0];if(r)await logger.log({guildId,eventKey:'report-claim',title:'Report Claimed',body:`Report #${r.report_number} claimed.`,actorUserId:reviewer.id}).catch(()=>{});return r||null}
 async addDetails({guildId,reportId,reviewer,details,logger}){const r=(await query("UPDATE reports SET review_notes=CONCAT(COALESCE(review_notes,''),$1),updated_at=NOW() WHERE guild_id=$2 AND id=$3 RETURNING *",[`\n${reviewer.tag}: ${details}`,guildId,reportId])).rows[0];if(r)await logger.log({guildId,eventKey:'report-note',title:'Report Details Added',body:`Report #${r.report_number}.`,actorUserId:reviewer.id}).catch(()=>{});return r||null}
 async reviewReport({guildId,reportId,reviewer,status,logger,details=null}){const s=String(status).toUpperCase();const r=(await query("UPDATE reports SET status=$1,reviewed_by_user_id=$2,reviewed_at=NOW(),review_notes=CASE WHEN $5::text IS NULL THEN review_notes ELSE CONCAT(COALESCE(review_notes,''),$5) END,updated_at=NOW() WHERE guild_id=$3 AND id=$4 RETURNING *",[s,reviewer.id,guildId,reportId,details?`\n${reviewer.tag}: ${details}`:null])).rows[0];if(r)await logger.log({guildId,eventKey:'report-review',title:'Report Reviewed',body:`Report #${r.report_number} marked ${s}.`,actorUserId:reviewer.id}).catch(()=>{});return r||null}
 async refreshReviewMessage({client,report}){const c=await sendable(client,report?.review_channel_id);const m=await c?.messages?.fetch(report?.review_message_id).catch(()=>null);if(!m)return false;await m.edit(buildReportReviewPayload(report));return true}
 async linkTicket({guildId,reportId,ticketId}){await query('UPDATE reports SET linked_ticket_id=$1,updated_at=NOW() WHERE guild_id=$2 AND id=$3',[ticketId,guildId,reportId])}
}
function buildReportReviewPayload(r){return{embeds:[createBaseEmbed({title:`Report #${r.report_number}`,description:[`Status: **${r.status||'OPEN'}**`,`Reporter: <@${r.reporter_user_id}>`,r.claimed_by_user_id?`Claimed By: <@${r.claimed_by_user_id}>`:'Claimed By: Not claimed',r.target_user_id?`Target: <@${r.target_user_id}>`:null,'','**Details**',truncate(r.details||'No details.',1500),r.review_notes?`\n**Review Notes**\n${truncate(r.review_notes,800)}`:null].filter(Boolean).join('\n'),color:SlickBotColors.WARNING,footer:'SlickBot Reports'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`${CustomIds.ReportClaimPrefix}${r.id}`).setLabel('Claim').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`${CustomIds.ReportResolvePrefix}${r.id}`).setLabel('Resolve').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`${CustomIds.ReportDismissPrefix}${r.id}`).setLabel('Dismiss').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`${CustomIds.ReportOpenTicketPrefix}${r.id}`).setLabel('Open Ticket').setStyle(ButtonStyle.Danger))]}}

class ApplicationService{
 async ensureDefaultType(g){const t=(await query("INSERT INTO application_types (guild_id,name,description,enabled) VALUES ($1,'Moderator','Apply to help moderate the SlickPickleNick community.',true) ON CONFLICT (guild_id,name) DO UPDATE SET updated_at=NOW() RETURNING *",[g])).rows[0];await this.ensureDefaultQuestions(t.id);return t}
 async ensureDefaultQuestions(id){const c=(await query('SELECT COUNT(*)::int AS count FROM application_questions WHERE application_type_id=$1',[id])).rows[0]?.count;if(c)return;for(const [i,q] of ['Why are you applying?','What relevant experience do you have?','What is your availability?'].entries())await query('INSERT INTO application_questions (application_type_id,question_text,required,display_order) VALUES ($1,$2,$3,$4)',[id,q,i<2,i+1])}
 async setupType(g,i){const t=(await query(`INSERT INTO application_types (guild_id,name,description,review_channel_id,pending_role_id,approved_role_id,auto_assign_approved_role,submission_confirmation_message,panel_title,panel_description,panel_color,panel_display_mode,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true) ON CONFLICT (guild_id,name) DO UPDATE SET description=COALESCE(EXCLUDED.description,application_types.description),review_channel_id=COALESCE(EXCLUDED.review_channel_id,application_types.review_channel_id),pending_role_id=COALESCE(EXCLUDED.pending_role_id,application_types.pending_role_id),approved_role_id=COALESCE(EXCLUDED.approved_role_id,application_types.approved_role_id),auto_assign_approved_role=EXCLUDED.auto_assign_approved_role,submission_confirmation_message=COALESCE(EXCLUDED.submission_confirmation_message,application_types.submission_confirmation_message),panel_title=COALESCE(EXCLUDED.panel_title,application_types.panel_title),panel_description=COALESCE(EXCLUDED.panel_description,application_types.panel_description),panel_color=COALESCE(EXCLUDED.panel_color,application_types.panel_color),panel_display_mode=COALESCE(EXCLUDED.panel_display_mode,application_types.panel_display_mode),enabled=true,updated_at=NOW() RETURNING *`,[g,i.name,i.description||null,i.reviewChannelId||null,i.pendingRoleId||null,i.approvedRoleId||null,Boolean(i.autoAssignApprovedRole),i.submissionConfirmationMessage||null,i.panelTitle||null,i.panelDescription||null,i.panelColor||null,i.panelDisplayMode||null])).rows[0];await this.ensureDefaultQuestions(t.id);return t}
 async getTypeByName(g,n){return(await query('SELECT * FROM application_types WHERE guild_id=$1 AND LOWER(name)=LOWER($2) LIMIT 1',[g,n])).rows[0]||null}
 async getTypeById(g,id){return(await query('SELECT * FROM application_types WHERE guild_id=$1 AND id=$2 LIMIT 1',[g,id])).rows[0]||null}
 async getQuestions(id){return(await query('SELECT * FROM application_questions WHERE application_type_id=$1 ORDER BY display_order,created_at',[id])).rows}
 async addQuestion(g,n,text,required=true,order=null){const t=await this.getTypeByName(g,n);if(!t)return null;return(await query('INSERT INTO application_questions (application_type_id,question_text,required,display_order) VALUES ($1,$2,$3,$4) RETURNING *',[t.id,text,required,order||((await this.getQuestions(t.id)).length+1)])).rows[0]}
 async clearQuestions(g,n){const t=await this.getTypeByName(g,n);if(!t)return null;await query('DELETE FROM application_questions WHERE application_type_id=$1',[t.id]);return t}
 async deleteType(g,n){const t=await this.getTypeByName(g,n);if(!t)return{ok:false,reason:'Application type not found.'};await query('DELETE FROM application_types WHERE guild_id=$1 AND id=$2',[g,t.id]);return{ok:true,type:t}}
 async startApplicationDm({interaction,logger,applicationType}){if((await query("SELECT id FROM application_submissions WHERE guild_id=$1 AND application_type_id=$2 AND applicant_user_id=$3 AND status='PENDING' LIMIT 1",[interaction.guildId,applicationType.id,interaction.user.id])).rowCount)return{ok:false,reason:'You already have a pending application for this type.'};let qs=await this.getQuestions(applicationType.id);if(!qs.length){await this.ensureDefaultQuestions(applicationType.id);qs=await this.getQuestions(applicationType.id)}const dm=await interaction.user.createDM().catch(()=>null);if(!dm)return{ok:false,reason:'I could not DM you. Please enable server DMs and try again.'};await query("UPDATE application_sessions SET status='CANCELLED' WHERE applicant_user_id=$1 AND status='ACTIVE'",[interaction.user.id]);const s=(await query("INSERT INTO application_sessions (guild_id,application_type_id,applicant_user_id,applicant_user_tag,current_index,answers,status) VALUES ($1,$2,$3,$4,0,'{}'::jsonb,'ACTIVE') RETURNING *",[interaction.guildId,applicationType.id,interaction.user.id,interaction.user.tag])).rows[0];await dm.send(questionPayload(applicationType.name,qs[0],0,qs.length));await logger.log({guildId:interaction.guildId,eventKey:'application-start',title:'Application Started',body:`${interaction.user.tag} started ${applicationType.name}.`,actorUserId:interaction.user.id}).catch(()=>{});return{ok:true,questionCount:qs.length,session:s}}
 async handleDmResponse({message}){if(message.author.bot||message.guild)return false;const s=(await query("SELECT s.*,t.name AS application_name FROM application_sessions s JOIN application_types t ON t.id=s.application_type_id WHERE s.applicant_user_id=$1 AND s.status='ACTIVE' ORDER BY s.updated_at DESC LIMIT 1",[message.author.id])).rows[0];if(!s)return false;const qs=await this.getQuestions(s.application_type_id),q=qs[s.current_index],answers=parse(s.answers,{});answers[q.question_text]=message.content||'[No text response]';const ni=s.current_index+1;if(ni<qs.length){await query('UPDATE application_sessions SET current_index=$1,answers=$2,updated_at=NOW() WHERE id=$3',[ni,json(answers),s.id]);await message.channel.send(questionPayload(s.application_name,qs[ni],ni,qs.length))}else{await query("UPDATE application_sessions SET current_index=$1,answers=$2,status='AWAITING_CONFIRMATION',updated_at=NOW() WHERE id=$3",[ni,json(answers),s.id]);await message.channel.send(confirmPayload(s.id,s.application_name,answers))}return true}
 async cancelSession({sessionId,user}){return(await query("UPDATE application_sessions SET status='CANCELLED',updated_at=NOW() WHERE id=$1 AND applicant_user_id=$2 AND status IN ('ACTIVE','AWAITING_CONFIRMATION') RETURNING *",[sessionId,user.id])).rows[0]||null}
 async submitSession({sessionId,user,client,logger}){const s=(await query("SELECT * FROM application_sessions WHERE id=$1 AND applicant_user_id=$2 AND status='AWAITING_CONFIRMATION' LIMIT 1",[sessionId,user.id])).rows[0];if(!s)return{ok:false,reason:'This application session is no longer active.'};const t=await this.getTypeById(s.guild_id,s.application_type_id),guild=await client.guilds.fetch(s.guild_id).catch(()=>null),r=await this.submitApplicationDirect({guildId:s.guild_id,guild,user,client,logger,applicationType:t,answers:parse(s.answers,{})});if(r.ok)await query("UPDATE application_sessions SET status='COMPLETED',completed_at=NOW() WHERE id=$1",[sessionId]);return{...r,applicationType:t}}
 async submitApplicationDirect({guildId,guild,user,client,logger,applicationType,answers}){if((await query("SELECT id FROM application_submissions WHERE guild_id=$1 AND application_type_id=$2 AND applicant_user_id=$3 AND status='PENDING' LIMIT 1",[guildId,applicationType.id,user.id])).rowCount)return{ok:false,reason:'You already have a pending application for this type.'};const n=Number((await query(next('application_submissions','submission_number'),[guildId])).rows[0].next_number),s=(await query("INSERT INTO application_submissions (guild_id,submission_number,application_type_id,application_name,applicant_user_id,applicant_user_tag,answers,status) VALUES ($1,$2,$3,$4,$5,$6,$7,'PENDING') RETURNING *",[guildId,n,applicationType.id,applicationType.name,user.id,user.tag,json(answers)])).rows[0];if(guild&&applicationType.pending_role_id)(await guild.members.fetch(user.id).catch(()=>null))?.roles.add(applicationType.pending_role_id).catch(()=>{});const c=await sendable(client,applicationType.review_channel_id);if(c)await c.send(buildApplicationReviewPayload(s,applicationType));await logger.log({guildId,eventKey:'application-submit',title:'Application Submitted',body:`Application #${n} submitted.`,actorUserId:user.id}).catch(()=>{});return{ok:true,submission:s}}
 async submitApplication({interaction,client,logger,applicationType,answers}){return this.submitApplicationDirect({guildId:interaction.guildId,guild:interaction.guild,user:interaction.user,client,logger,applicationType,answers})}
 async reviewApplication({interaction,logger,submissionId,status}){const s=(await query('SELECT s.*,t.pending_role_id,t.approved_role_id,t.auto_assign_approved_role FROM application_submissions s JOIN application_types t ON t.id=s.application_type_id WHERE s.guild_id=$1 AND s.id=$2 LIMIT 1',[interaction.guildId,submissionId])).rows[0];if(!s)return null;const st=String(status).toUpperCase(),u=(await query('UPDATE application_submissions SET status=$1,reviewed_by_user_id=$2,reviewed_at=NOW(),updated_at=NOW() WHERE id=$3 RETURNING *',[st,interaction.user.id,s.id])).rows[0],m=await interaction.guild.members.fetch(s.applicant_user_id).catch(()=>null);if(m&&s.pending_role_id)await m.roles.remove(s.pending_role_id).catch(()=>{});if(m&&st==='APPROVED'&&s.auto_assign_approved_role&&s.approved_role_id)await m.roles.add(s.approved_role_id).catch(()=>{});await logger.log({guildId:interaction.guildId,eventKey:'application-review',title:'Application Reviewed',body:`Application #${s.submission_number} marked ${st}.`,actorUserId:interaction.user.id}).catch(()=>{});return u}
}
const questionPayload=(name,q,i,total)=>({embeds:[createBaseEmbed({title:`${name} Application`,description:`**Question ${i+1} of ${total}**\n${q.question_text}\n\nReply to this DM with your answer.`,footer:'SlickBot Applications'})]});
const confirmPayload=(id,name,a)=>({embeds:[createBaseEmbed({title:`Review ${name} Application`,description:`${answerText(a)}\n\nSubmit or cancel below.`,color:SlickBotColors.INFO,footer:'SlickBot Applications'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`${CustomIds.ApplicationSubmitPrefix}${id}`).setLabel('Submit Application').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`${CustomIds.ApplicationCancelPrefix}${id}`).setLabel('Cancel').setStyle(ButtonStyle.Danger))]});
function buildApplicationReviewPayload(s,t){return{embeds:[createBaseEmbed({title:`${s.application_name} Application #${s.submission_number}`,description:`Applicant: <@${s.applicant_user_id}>\n\n**Answers**\n${answerText(s.answers)}`,footer:'SlickBot Applications'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`${CustomIds.ApplicationApprovePrefix}${s.id}`).setLabel('Approve').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`${CustomIds.ApplicationDenyPrefix}${s.id}`).setLabel('Deny').setStyle(ButtonStyle.Danger))]}}

class AppealService{
 async getConfig(g){return(await query('SELECT * FROM appeal_configs WHERE guild_id=$1 LIMIT 1',[g])).rows[0]||null}
 async updateConfig(g,i){return(await query(`INSERT INTO appeal_configs (guild_id,review_channel_id,dm_decision_enabled,dm_include_submission,panel_title,panel_description,panel_color,panel_display_mode) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (guild_id) DO UPDATE SET review_channel_id=COALESCE(EXCLUDED.review_channel_id,appeal_configs.review_channel_id),dm_decision_enabled=EXCLUDED.dm_decision_enabled,dm_include_submission=EXCLUDED.dm_include_submission,panel_title=COALESCE(EXCLUDED.panel_title,appeal_configs.panel_title),panel_description=COALESCE(EXCLUDED.panel_description,appeal_configs.panel_description),panel_color=COALESCE(EXCLUDED.panel_color,appeal_configs.panel_color),panel_display_mode=COALESCE(EXCLUDED.panel_display_mode,appeal_configs.panel_display_mode),updated_at=NOW() RETURNING *`,[g,i.reviewChannelId||null,Boolean(i.dmDecisionEnabled),Boolean(i.dmIncludeSubmission),i.panelTitle||null,i.panelDescription||null,i.panelColor||null,i.panelDisplayMode||null])).rows[0]}
 async submitAppeal({interaction,client,logger,caseNumber,reason,details}){const n=Number((await query(next('appeals','appeal_number'),[interaction.guildId])).rows[0].next_number),a=(await query("INSERT INTO appeals (guild_id,appeal_number,appellant_user_id,appellant_user_tag,case_number,reason,details,status) VALUES ($1,$2,$3,$4,$5,$6,$7,'PENDING') RETURNING *",[interaction.guildId,n,interaction.user.id,interaction.user.tag,caseNumber||null,reason,details||null])).rows[0],c=await sendable(client,(await this.getConfig(interaction.guildId))?.review_channel_id);if(c)await c.send(buildAppealReviewPayload(a));await logger.log({guildId:interaction.guildId,eventKey:'appeal-submit',title:'Appeal Submitted',body:`Appeal #${n} submitted.`,actorUserId:interaction.user.id}).catch(()=>{});return a}
 async reviewAppeal({interaction,client,logger,appealId,status,reason=null}){const st=String(status).toUpperCase(),a=(await query('UPDATE appeals SET status=$1,reviewed_by_user_id=$2,reviewed_at=NOW(),decision_reason=$3,updated_at=NOW() WHERE guild_id=$4 AND id=$5 RETURNING *',[st,interaction.user.id,reason,interaction.guildId,appealId])).rows[0];if(!a)return null;if((await this.getConfig(interaction.guildId))?.dm_decision_enabled){const u=await client.users.fetch(a.appellant_user_id).catch(()=>null);await u?.send({embeds:[createBaseEmbed({title:`Appeal #${a.appeal_number} Decision`,description:`Status: **${st}**${reason?`\nReason: ${reason}`:''}`,color:st==='APPROVED'?SlickBotColors.SUCCESS:SlickBotColors.WARNING})]}).catch(()=>{})}await logger.log({guildId:interaction.guildId,eventKey:'appeal-review',title:'Appeal Reviewed',body:`Appeal #${a.appeal_number} marked ${st}.`,actorUserId:interaction.user.id}).catch(()=>{});return a}
}
function buildAppealReviewPayload(a){return{embeds:[createBaseEmbed({title:`Appeal #${a.appeal_number}`,description:`Appellant: <@${a.appellant_user_id}>\n${a.case_number?`Case: **#${a.case_number}**`:'Case: Not provided'}\n\n**Reason**\n${truncate(a.reason,1200)}\n\n**Details**\n${truncate(a.details||'No extra details provided.',1200)}`,color:SlickBotColors.INFO,footer:'SlickBot Appeals'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`${CustomIds.AppealApproveReasonPrefix}${a.id}`).setLabel('Approve').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`${CustomIds.AppealDenyReasonPrefix}${a.id}`).setLabel('Deny').setStyle(ButtonStyle.Danger))]}}

function input(id,label,style=TextInputStyle.Paragraph,required=true,max=1000){return new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(style).setRequired(required).setMaxLength(max))}
function buildTicketModal(t=null){const qs=parse(t?.questions,[]),m=new ModalBuilder().setCustomId(`${CustomIds.TicketModalPrefix}${t?.id||'default'}`).setTitle(`${t?.label||t?.name||'Support'} Ticket`.slice(0,45)),rows=[input('subject','Subject',TextInputStyle.Short,true,100)];for(const [i,q] of (qs.length?qs.slice(0,4):[{label:'How can staff help?',required:true}]).entries())rows.push(input(`q${i}`,String(q.label||`Question ${i+1}`).slice(0,45),TextInputStyle.Paragraph,q.required!==false,1500));return m.addComponents(...rows)}
const buildReportModal=()=>new ModalBuilder().setCustomId(CustomIds.ReportModal).setTitle('Submit Report').addComponents(input('target','User ID / Username / Message Link',TextInputStyle.Short,false,200),input('details','What happened?',TextInputStyle.Paragraph,true,1800));
const buildReportDetailsModal=id=>new ModalBuilder().setCustomId(`${CustomIds.ReportDetailsModalPrefix}${id}`).setTitle('Add Report Details').addComponents(input('details','Details to add',TextInputStyle.Paragraph,true,1500));
const buildAppealModal=()=>new ModalBuilder().setCustomId(CustomIds.AppealModal).setTitle('Submit Appeal').addComponents(input('case_number','Case number, if known',TextInputStyle.Short,false,20),input('reason','Why should this be reviewed?',TextInputStyle.Paragraph,true,1000),input('details','Additional context',TextInputStyle.Paragraph,false,1000));
const buildAppealReasonModal=(id,status)=>new ModalBuilder().setCustomId(`${CustomIds.AppealReasonModalPrefix}${status}:${id}`).setTitle(`${status==='APPROVED'?'Approve':'Deny'} Appeal With Reason`).addComponents(input('reason','Decision reason',TextInputStyle.Paragraph,false,1000));
const buildApplicationModal=(id,title='Application')=>new ModalBuilder().setCustomId(`${CustomIds.ApplicationModalPrefix}${id}`).setTitle(title.slice(0,45)).addComponents(input('why','Why are you applying?'),input('experience','Relevant experience'),input('availability','Availability / extra notes',TextInputStyle.Paragraph,false,1000));
module.exports={TicketService,ReportService,ApplicationService,AppealService,buildTicketModal,buildReportModal,buildReportDetailsModal,buildApplicationModal,buildAppealModal,buildAppealReasonModal,buildReportReviewPayload,buildApplicationReviewPayload,buildAppealReviewPayload};
