const { updatePublishedPanelsForRefs } = require('./publishedPanelService');
const { buildPublicTicketPanel,buildPublicReportPanel,buildPublicApplicationPanel,buildPublicAppealPanel }=require('../support/supportUi');
const { TicketService,ReportService,ApplicationService,AppealService }=require('../support/supportService');
const roles=require('../community/rolePanelService');const {BirthdayService}=require('../community/birthdayService');
const tickets=new TicketService(),reports=new ReportService(),apps=new ApplicationService(),appeals=new AppealService(),birthdays=new BirthdayService();
async function buildPayload(g,t,r='*'){if(t==='ticket')return buildPublicTicketPanel(await tickets.listTypes(g),await tickets.getConfig(g));if(t==='report')return buildPublicReportPanel(await reports.getConfig(g));if(t==='appeal')return buildPublicAppealPanel(await appeals.getConfig(g));if(t==='application'){const x=await apps.getTypeById(g,r)||await apps.getTypeByName(g,r);return x?buildPublicApplicationPanel(x):null;}if(t==='birthday')return birthdays.buildPublicPanel(g);if(t==='role'){const p=await roles.getPanelById(g,r)||await roles.getPanelByName(g,r);return p?roles.buildRolePanelMessage(p):null;}return null;}
async function refreshPublishedPanel(client,g,t,r='*',extra=[]){if(t==='role'){const p=await roles.getPanelById(g,r)||await roles.getPanelByName(g,r);return p?roles.updatePublishedRolePanelMessages(client,g,p):{updated:0,total:0};}const payload=await buildPayload(g,t,r);return payload?updatePublishedPanelsForRefs(client,{guildId:g,panelType:t,panelRefs:[...new Set([String(r),...extra.map(String)])],payload}):{updated:0,total:0};}
async function refreshPublishedPanelFromResult(c,g,r){return r?.panelType?refreshPublishedPanel(c,g,r.panelType,r.panelRef||'*',r.altPanelRefs||[]):{updated:0,total:0};}
function formatRefreshSummary(r){return r?.total?`\nLive panels updated: **${r.updated}/${r.total}**.`:'';}
module.exports={buildPayload,refreshPublishedPanel,refreshPublishedPanelFromResult,formatRefreshSummary};
