const { AttachmentBuilder, EmbedBuilder } = require('discord.js');
const { query } = require('../../services/db');
const { truncate } = require('../../utils/format');
const { getLogEvent, getLogModule } = require('./logEventCatalog');
const LogDeliveryMode=Object.freeze({IMMEDIATE:'IMMEDIATE',BATCHED:'BATCHED',DISABLED:'DISABLED'});
class LoggingService{
 constructor(client){this.client=client;}
 async writeAudit(input){await query(`INSERT INTO audit_logs (guild_id,actor_user_id,action_key,target_type,target_id,severity,summary,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,[input.guildId,input.actorUserId||null,input.actionKey,input.targetType||null,input.targetId||null,input.severity||'INFO',input.summary,input.metadata?JSON.stringify(input.metadata):null]);}
 async getLogRouting(guildId,eventKey){const event=getLogEvent(eventKey)||{key:eventKey,moduleKey:eventKey,label:eventKey,defaultDelivery:'IMMEDIATE'};const moduleInfo=getLogModule(event.moduleKey);const [m,e]=await Promise.all([query(`SELECT * FROM log_module_settings WHERE guild_id=$1 AND module_key=$2 LIMIT 1`,[guildId,event.moduleKey]),query(`SELECT * FROM log_settings WHERE guild_id=$1 AND event_key=$2 LIMIT 1`,[guildId,eventKey])]);const ms=m.rows[0]||null,es=e.rows[0]||null;if(es&&(es.enabled===false||es.delivery_mode==='DISABLED'))return null;if(ms&&(ms.enabled===false||ms.delivery_mode==='DISABLED')&&(!es||!es.channel_id))return null;const channelId=es?.channel_id||ms?.channel_id||null;if(!channelId)return null;const deliveryMode=es?.delivery_mode||ms?.delivery_mode||event.defaultDelivery||'IMMEDIATE';if(deliveryMode==='DISABLED')return null;return{guildId,eventKey,moduleKey:event.moduleKey,channelId,deliveryMode,batchIntervalSeconds:es?.batch_interval_seconds||ms?.batch_interval_seconds||300,maxBatchItems:es?.max_batch_items||ms?.max_batch_items||25,event,module:moduleInfo};}
 async log(input){const routing=await this.getLogRouting(input.guildId,input.eventKey);if(!routing)return{sent:false,reason:'NO_LOG_MODULE_CHANNEL'};if(routing.deliveryMode==='IMMEDIATE'){await this.sendImmediate(input,routing);return{sent:true,deliveryMode:'IMMEDIATE',moduleKey:routing.moduleKey};}await query(`INSERT INTO log_queue_items (guild_id,event_key,module_key,title,body,metadata) VALUES ($1,$2,$3,$4,$5,$6)`,[input.guildId,input.eventKey,routing.moduleKey,input.title,input.body,input.metadata?JSON.stringify(input.metadata):null]);return{sent:true,deliveryMode:'BATCHED',moduleKey:routing.moduleKey};}
 async sendImmediate(input,routing){const channel=await this.fetchSendableChannel(routing?.channelId);if(!channel)return;const embed=new EmbedBuilder().setColor(0x7869ff).setTitle(input.title).setDescription(truncate(input.body,4000)).setFooter({text:`${routing.module?.label||routing.moduleKey} • ${routing.event?.label||input.eventKey}`}).setTimestamp();await channel.send({embeds:[embed]});}
 async flushDueBatches(){const p=await query(`SELECT DISTINCT guild_id,event_key FROM log_queue_items WHERE flushed_at IS NULL ORDER BY guild_id,event_key`);let n=0;for(const r of p.rows)n+=await this.flushBatch(r.guild_id,r.event_key);return n;}
 async flushGuildBatches(guildId){const p=await query(`SELECT DISTINCT event_key FROM log_queue_items WHERE guild_id=$1 AND flushed_at IS NULL ORDER BY event_key`,[guildId]);let n=0;for(const r of p.rows)n+=await this.flushBatch(guildId,r.event_key);return n;}
 async flushBatch(guildId,eventKey,takeOverride=null){const routing=await this.getLogRouting(guildId,eventKey);if(!routing||routing.deliveryMode!=='BATCHED')return 0;const q=await query(`SELECT * FROM log_queue_items WHERE guild_id=$1 AND event_key=$2 AND flushed_at IS NULL ORDER BY created_at LIMIT $3`,[guildId,eventKey,takeOverride||routing.maxBatchItems||25]);if(!q.rowCount)return 0;const channel=await this.fetchSendableChannel(routing.channelId);if(!channel)return 0;const lines=q.rows.map(i=>`[${new Date(i.created_at).toISOString()}] ${i.title}\n${i.body}`),body=lines.join('\n\n'),summary=lines.slice(0,10).join('\n\n');const embed=new EmbedBuilder().setColor(0x5aa7ff).setTitle(`${routing.module?.label||routing.moduleKey} Batch`).setDescription(truncate(summary,3900)).setFooter({text:`${q.rowCount} log item${q.rowCount===1?'':'s'} • ${routing.event?.label||eventKey}`}).setTimestamp();if(body.length>3900)await channel.send({embeds:[embed],files:[new AttachmentBuilder(Buffer.from(body,'utf8'),{name:`${routing.moduleKey}-${eventKey}-${Date.now()}.txt`})]});else await channel.send({embeds:[embed]});await query(`UPDATE log_queue_items SET flushed_at=NOW() WHERE id=ANY($1)`,[q.rows.map(i=>i.id)]);return q.rowCount;}
 async fetchSendableChannel(id){if(!id)return null;const c=await this.client.channels.fetch(id).catch(()=>null);return c&&c.isTextBased?.()&&typeof c.send==='function'?c:null;}
}
module.exports={LoggingService,LogDeliveryMode};
