const {query,closeDatabase}=require('./db');const {ensureJoinToCreateSchema}=require('../modules/community/joinToCreateService');
async function initDatabase(){
 await query('CREATE EXTENSION IF NOT EXISTS pgcrypto;');
 const sql=[
`CREATE TABLE IF NOT EXISTS guild_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL,guild_name TEXT,timezone TEXT NOT NULL DEFAULT 'America/New_York',default_log_channel_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS module_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,module_key TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT false,log_channel_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,module_key))`,
`CREATE TABLE IF NOT EXISTS permission_teams(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT,is_system_team BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,name))`,
`CREATE TABLE IF NOT EXISTS permission_team_roles(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,team_id TEXT NOT NULL REFERENCES permission_teams(id) ON DELETE CASCADE,role_id TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(team_id,role_id))`,
`CREATE TABLE IF NOT EXISTS permission_team_users(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,team_id TEXT NOT NULL REFERENCES permission_teams(id) ON DELETE CASCADE,user_id TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(team_id,user_id))`,
`CREATE TABLE IF NOT EXISTS command_permissions(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,team_id TEXT NOT NULL REFERENCES permission_teams(id) ON DELETE CASCADE,action_key TEXT NOT NULL,allow BOOLEAN NOT NULL DEFAULT true,channel_scope TEXT NOT NULL DEFAULT '*',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(team_id,action_key,channel_scope))`,
`CREATE TABLE IF NOT EXISTS command_permission_levels(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,action_key TEXT NOT NULL,required_level TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,action_key))`,
`CREATE TABLE IF NOT EXISTS module_permission_levels(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,module_key TEXT NOT NULL,required_level TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,module_key))`,
`CREATE TABLE IF NOT EXISTS role_permission_levels(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,role_id TEXT NOT NULL,permission_level TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,role_id))`,
`CREATE TABLE IF NOT EXISTS team_permission_levels(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,team_id TEXT NOT NULL REFERENCES permission_teams(id) ON DELETE CASCADE,permission_level TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,team_id))`,
`CREATE TABLE IF NOT EXISTS public_action_permissions(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,action_key TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,action_key))`,
`CREATE TABLE IF NOT EXISTS role_action_permissions(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,role_id TEXT NOT NULL,action_key TEXT NOT NULL,allow BOOLEAN NOT NULL DEFAULT true,channel_scope TEXT NOT NULL DEFAULT '*',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,role_id,action_key,channel_scope))`,
`CREATE TABLE IF NOT EXISTS module_permission_targets(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,module_key TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,allow BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,module_key,target_type,target_id))`,
`CREATE TABLE IF NOT EXISTS permission_ignored_users(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,user_id TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,user_id))`,
`CREATE TABLE IF NOT EXISTS permission_default_versions(guild_id TEXT PRIMARY KEY,seeded_version TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS bot_presence_settings(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL,status TEXT NOT NULL DEFAULT 'online',activity_type TEXT NOT NULL DEFAULT 'NONE',activity_text TEXT,activity_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS log_module_settings(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,module_key TEXT NOT NULL,delivery_mode TEXT NOT NULL DEFAULT 'IMMEDIATE',channel_id TEXT,batch_interval_seconds INTEGER NOT NULL DEFAULT 300,max_batch_items INTEGER NOT NULL DEFAULT 25,enabled BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,module_key))`,
`CREATE TABLE IF NOT EXISTS log_settings(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,event_key TEXT NOT NULL,delivery_mode TEXT,channel_id TEXT,batch_interval_seconds INTEGER NOT NULL DEFAULT 300,max_batch_items INTEGER NOT NULL DEFAULT 25,enabled BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,event_key))`,
`CREATE TABLE IF NOT EXISTS log_queue_items(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,event_key TEXT NOT NULL,module_key TEXT,title TEXT NOT NULL,body TEXT NOT NULL,metadata JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),flushed_at TIMESTAMPTZ)`,
`CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,actor_user_id TEXT,action_key TEXT NOT NULL,target_type TEXT,target_id TEXT,severity TEXT NOT NULL DEFAULT 'INFO',summary TEXT NOT NULL,metadata JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS moderation_cases(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,case_number INTEGER NOT NULL,target_user_id TEXT NOT NULL,target_user_tag TEXT,actor_user_id TEXT,action_type TEXT NOT NULL,reason TEXT,status TEXT NOT NULL DEFAULT 'OPEN',duration_seconds INTEGER,expires_at TIMESTAMPTZ,evidence TEXT,metadata JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,case_number))`,
`CREATE TABLE IF NOT EXISTS user_notes(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,note_number INTEGER NOT NULL,target_user_id TEXT NOT NULL,target_user_tag TEXT,actor_user_id TEXT,note TEXT NOT NULL,is_active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,note_number))`,
`CREATE TABLE IF NOT EXISTS ticket_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,category_id TEXT,log_channel_id TEXT,staff_role_id TEXT,staff_team_id TEXT,escalated_role_id TEXT,escalated_team_id TEXT,ticket_limit INTEGER NOT NULL DEFAULT 1,transcript_enabled BOOLEAN NOT NULL DEFAULT true,naming_format TEXT NOT NULL DEFAULT 'ticket-{username}-{number}',panel_title TEXT,panel_description TEXT,panel_color TEXT,panel_display_mode TEXT DEFAULT 'BUTTONS',panel_header_image_url TEXT,close_delete_seconds INTEGER NOT NULL DEFAULT 10,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS ticket_types(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,name TEXT NOT NULL,label TEXT,description TEXT,category_id TEXT,log_channel_id TEXT,staff_role_id TEXT,staff_team_id TEXT,escalated_role_id TEXT,escalated_team_id TEXT,ticket_limit INTEGER NOT NULL DEFAULT 1,transcript_enabled BOOLEAN NOT NULL DEFAULT true,naming_format TEXT NOT NULL DEFAULT 'ticket-{username}-{number}',questions JSONB DEFAULT '[]'::jsonb,enabled BOOLEAN NOT NULL DEFAULT true,panel_header_image_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,name))`,
`CREATE TABLE IF NOT EXISTS tickets(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,ticket_number INTEGER NOT NULL,channel_id TEXT NOT NULL,opener_user_id TEXT NOT NULL,opener_user_tag TEXT,claimed_by_user_id TEXT,type TEXT NOT NULL DEFAULT 'Admin Support',subject TEXT NOT NULL,details TEXT,status TEXT NOT NULL DEFAULT 'OPEN',priority TEXT NOT NULL DEFAULT 'NORMAL',close_reason TEXT,closed_by_user_id TEXT,transcript_sent BOOLEAN NOT NULL DEFAULT false,ticket_type_id TEXT,reviewer_role_id TEXT,reviewer_role_ids JSONB NOT NULL DEFAULT '[]'::jsonb,escalated_to_role_id TEXT,escalated_by_user_id TEXT,escalated_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),closed_at TIMESTAMPTZ,UNIQUE(guild_id,ticket_number))`,
`CREATE TABLE IF NOT EXISTS report_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,review_channel_id TEXT,ping_role_id TEXT,ping_team_id TEXT,panel_title TEXT,panel_description TEXT,panel_color TEXT,panel_display_mode TEXT DEFAULT 'BUTTONS',panel_header_image_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,report_number INTEGER NOT NULL,reporter_user_id TEXT NOT NULL,reporter_user_tag TEXT,target_user_id TEXT,target_user_tag TEXT,report_type TEXT NOT NULL DEFAULT 'General Report',message_link TEXT,details TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',claimed_by_user_id TEXT,reviewed_by_user_id TEXT,reviewed_at TIMESTAMPTZ,review_notes TEXT,review_channel_id TEXT,review_message_id TEXT,linked_ticket_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,report_number))`,
`CREATE TABLE IF NOT EXISTS application_types(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT,review_channel_id TEXT,pending_role_id TEXT,approved_role_id TEXT,auto_assign_approved_role BOOLEAN NOT NULL DEFAULT false,submission_confirmation_message TEXT,panel_title TEXT,panel_description TEXT,panel_color TEXT,panel_display_mode TEXT DEFAULT 'BUTTONS',panel_header_image_url TEXT,enabled BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,name))`,
`CREATE TABLE IF NOT EXISTS application_questions(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,application_type_id TEXT NOT NULL REFERENCES application_types(id) ON DELETE CASCADE,question_text TEXT NOT NULL,required BOOLEAN NOT NULL DEFAULT true,display_order INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS application_sessions(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,application_type_id TEXT NOT NULL REFERENCES application_types(id) ON DELETE CASCADE,applicant_user_id TEXT NOT NULL,applicant_user_tag TEXT,current_index INTEGER NOT NULL DEFAULT 0,answers JSONB NOT NULL DEFAULT '{}'::jsonb,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ)`,
`CREATE TABLE IF NOT EXISTS application_submissions(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,submission_number INTEGER NOT NULL,application_type_id TEXT NOT NULL REFERENCES application_types(id) ON DELETE CASCADE,application_name TEXT NOT NULL,applicant_user_id TEXT NOT NULL,applicant_user_tag TEXT,answers JSONB,status TEXT NOT NULL DEFAULT 'PENDING',reviewed_by_user_id TEXT,reviewed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,submission_number))`,
`CREATE TABLE IF NOT EXISTS appeal_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,review_channel_id TEXT,dm_decision_enabled BOOLEAN NOT NULL DEFAULT false,dm_include_submission BOOLEAN NOT NULL DEFAULT false,panel_title TEXT,panel_description TEXT,panel_color TEXT,panel_display_mode TEXT DEFAULT 'BUTTONS',panel_header_image_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS appeals(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,appeal_number INTEGER NOT NULL,appellant_user_id TEXT NOT NULL,appellant_user_tag TEXT,case_number INTEGER,reason TEXT NOT NULL,details TEXT,status TEXT NOT NULL DEFAULT 'PENDING',reviewed_by_user_id TEXT,reviewed_at TIMESTAMPTZ,decision_reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,appeal_number))`,
`CREATE TABLE IF NOT EXISTS welcome_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,channel_id TEXT,enabled BOOLEAN NOT NULL DEFAULT true,message_template TEXT,embed_title TEXT,embed_description TEXT,embed_color TEXT,dm_enabled BOOLEAN NOT NULL DEFAULT false,dm_message_template TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS welcome_auto_roles(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,role_id TEXT NOT NULL,added_by_user_id TEXT,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,role_id))`,
`CREATE TABLE IF NOT EXISTS role_panels(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,name TEXT NOT NULL,title TEXT,description TEXT,selection_mode TEXT NOT NULL DEFAULT 'MULTI',panel_color TEXT,panel_display_mode TEXT NOT NULL DEFAULT 'BUTTONS',panel_header_image_url TEXT,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,name))`,
`CREATE TABLE IF NOT EXISTS role_panel_options(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,panel_id TEXT NOT NULL REFERENCES role_panels(id) ON DELETE CASCADE,role_id TEXT,role_ids JSONB NOT NULL DEFAULT '[]'::jsonb,label TEXT,emoji TEXT,description TEXT,button_color TEXT NOT NULL DEFAULT '#5865f2',display_order INTEGER NOT NULL DEFAULT 1,active BOOLEAN NOT NULL DEFAULT true,option_key TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(panel_id,option_key))`,
`CREATE TABLE IF NOT EXISTS giveaway_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,default_channel_id TEXT,ping_role_id TEXT,host_role_id TEXT,panel_color TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS giveaways(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,giveaway_number INTEGER NOT NULL,channel_id TEXT NOT NULL,message_id TEXT,host_user_id TEXT,prize TEXT NOT NULL,description TEXT,winner_count INTEGER NOT NULL DEFAULT 1,end_at TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',winner_user_ids JSONB NOT NULL DEFAULT '[]'::jsonb,ended_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,giveaway_number))`,
`CREATE TABLE IF NOT EXISTS giveaway_entries(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,giveaway_id TEXT NOT NULL REFERENCES giveaways(id) ON DELETE CASCADE,user_id TEXT NOT NULL,user_tag TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(giveaway_id,user_id))`,
`CREATE TABLE IF NOT EXISTS birthday_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,channel_id TEXT,birthday_role_id TEXT,announcement_template TEXT,timezone TEXT NOT NULL DEFAULT 'America/New_York',enabled BOOLEAN NOT NULL DEFAULT true,panel_header_image_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS birthday_profiles(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,user_id TEXT NOT NULL,user_tag TEXT,birth_month INTEGER NOT NULL,birth_day INTEGER NOT NULL,timezone TEXT,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,user_id))`,
`CREATE TABLE IF NOT EXISTS birthday_announcements(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,user_id TEXT NOT NULL,announcement_date TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,user_id,announcement_date))`,
`CREATE TABLE IF NOT EXISTS scheduled_message_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,default_channel_id TEXT,enabled BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS scheduled_messages(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,schedule_number INTEGER NOT NULL,channel_id TEXT NOT NULL,created_by_user_id TEXT,content TEXT NOT NULL,send_at TIMESTAMPTZ NOT NULL,repeat_mode TEXT NOT NULL DEFAULT 'NONE',status TEXT NOT NULL DEFAULT 'SCHEDULED',last_sent_at TIMESTAMPTZ,cancelled_by_user_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,schedule_number))`,
`CREATE TABLE IF NOT EXISTS server_stats_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,enabled BOOLEAN NOT NULL DEFAULT true,member_channel_id TEXT,human_channel_id TEXT,bot_channel_id TEXT,voice_channel_id TEXT,member_template TEXT NOT NULL DEFAULT 'Members: {members}',human_template TEXT NOT NULL DEFAULT 'Humans: {humans}',bot_template TEXT NOT NULL DEFAULT 'Bots: {bots}',voice_template TEXT NOT NULL DEFAULT 'In Voice: {voice}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS leveling_configs(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT UNIQUE NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,enabled BOOLEAN NOT NULL DEFAULT true,xp_min INTEGER NOT NULL DEFAULT 15,xp_max INTEGER NOT NULL DEFAULT 25,cooldown_seconds INTEGER NOT NULL DEFAULT 60,minimum_message_length INTEGER NOT NULL DEFAULT 3,level_up_channel_id TEXT,level_up_message TEXT NOT NULL DEFAULT 'Congratulations {user}! You reached level **{level}**.',level_up_announce_mode TEXT NOT NULL DEFAULT 'ALL_LEVELS',ignored_channel_ids JSONB NOT NULL DEFAULT '[]'::jsonb,ignored_role_ids JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS leveling_profiles(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,user_id TEXT NOT NULL,user_tag TEXT,xp BIGINT NOT NULL DEFAULT 0,level INTEGER NOT NULL DEFAULT 0,message_count BIGINT NOT NULL DEFAULT 0,last_xp_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,user_id))`,
`CREATE TABLE IF NOT EXISTS leveling_role_rewards(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,level INTEGER NOT NULL,role_id TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,level,role_id))`,
`CREATE TABLE IF NOT EXISTS leveling_multiplier_roles(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL REFERENCES guild_configs(guild_id) ON DELETE CASCADE,role_id TEXT NOT NULL,multiplier NUMERIC(8,2) NOT NULL DEFAULT 1,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,role_id))`,
`CREATE TABLE IF NOT EXISTS published_panels(id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,guild_id TEXT NOT NULL,panel_type TEXT NOT NULL,panel_ref TEXT NOT NULL DEFAULT '*',channel_id TEXT NOT NULL,message_id TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(guild_id,channel_id,message_id))`
 ];
 for(const statement of sql)await query(statement);
 const alters=[
 `ALTER TABLE ticket_configs ADD COLUMN IF NOT EXISTS staff_team_id TEXT`,`ALTER TABLE ticket_configs ADD COLUMN IF NOT EXISTS escalated_role_id TEXT`,`ALTER TABLE ticket_configs ADD COLUMN IF NOT EXISTS escalated_team_id TEXT`,`ALTER TABLE ticket_configs ADD COLUMN IF NOT EXISTS panel_header_image_url TEXT`,
 `ALTER TABLE ticket_types ADD COLUMN IF NOT EXISTS staff_team_id TEXT`,`ALTER TABLE ticket_types ADD COLUMN IF NOT EXISTS escalated_role_id TEXT`,`ALTER TABLE ticket_types ADD COLUMN IF NOT EXISTS escalated_team_id TEXT`,`ALTER TABLE ticket_types ADD COLUMN IF NOT EXISTS panel_header_image_url TEXT`,
 `ALTER TABLE tickets ADD COLUMN IF NOT EXISTS reviewer_role_ids JSONB NOT NULL DEFAULT '[]'::jsonb`,`ALTER TABLE report_configs ADD COLUMN IF NOT EXISTS panel_header_image_url TEXT`,`ALTER TABLE application_types ADD COLUMN IF NOT EXISTS panel_header_image_url TEXT`,`ALTER TABLE appeal_configs ADD COLUMN IF NOT EXISTS panel_header_image_url TEXT`,`ALTER TABLE birthday_configs ADD COLUMN IF NOT EXISTS panel_header_image_url TEXT`,`ALTER TABLE role_panels ADD COLUMN IF NOT EXISTS panel_header_image_url TEXT`,`ALTER TABLE role_panel_options ADD COLUMN IF NOT EXISTS option_key TEXT`,`ALTER TABLE role_panel_options ADD COLUMN IF NOT EXISTS role_ids JSONB NOT NULL DEFAULT '[]'::jsonb`];
 for(const statement of alters)await query(statement).catch(()=>{});
 await ensureJoinToCreateSchema(query);
 const indexes=[`CREATE INDEX IF NOT EXISTS idx_tickets_channel ON tickets(guild_id,channel_id)`,`CREATE INDEX IF NOT EXISTS idx_log_queue_pending ON log_queue_items(guild_id,event_key,flushed_at)`,`CREATE INDEX IF NOT EXISTS idx_published_panels ON published_panels(guild_id,panel_type,panel_ref,active)`,`CREATE INDEX IF NOT EXISTS idx_scheduled_due ON scheduled_messages(status,send_at)`,`CREATE INDEX IF NOT EXISTS idx_giveaways_due ON giveaways(status,end_at)`];for(const statement of indexes)await query(statement);
}
if(require.main===module)initDatabase().then(async()=>{console.log('Database initialized.');await closeDatabase();}).catch(async e=>{console.error('Database initialization failed:',e);await closeDatabase().catch(()=>{});process.exit(1);});
module.exports={initDatabase};
