const { ChannelType, SlashCommandBuilder } = require('discord.js');
const { ModuleKeys } = require('../modules/moduleRegistry');
const { ActionKeys } = require('../modules/permissions/actionKeys');
const { replyPrivate } = require('../utils/reply');
const { AppealService } = require('../modules/support/supportService');
const { buildAppealsPanel, buildPublicAppealPanel } = require('../modules/support/supportUi');
const { createSuccessEmbed } = require('../modules/ui/uiService');
const { recordPublishedPanel } = require('../modules/panels/publishedPanelService');
const { refreshPublishedPanel, formatRefreshSummary } = require('../modules/panels/panelUpdateService');
const appeals = new AppealService();
module.exports = { data: new SlashCommandBuilder().setName('appeal').setDescription('Appeal system tools.')
  .addSubcommand((s)=>s.setName('manager').setDescription('Open the appeal manager panel.'))
  .addSubcommand((s)=>s.setName('setup').setDescription('Set appeal review settings.').addChannelOption((o)=>o.setName('review_channel').setDescription('Private staff appeal review channel.').addChannelTypes(ChannelType.GuildText).setRequired(true)).addBooleanOption((o)=>o.setName('dm_decision').setDescription('DM users when their appeal is approved or denied.').setRequired(false)).addBooleanOption((o)=>o.setName('dm_include_submission').setDescription('Include original appeal submission in the decision DM.').setRequired(false)).addStringOption((o)=>o.setName('panel_title').setDescription('Public appeal panel title.').setRequired(false).setMaxLength(100)).addStringOption((o)=>o.setName('panel_description').setDescription('Public appeal panel description.').setRequired(false).setMaxLength(800)).addStringOption((o)=>o.setName('panel_color').setDescription('Panel accent color, example: #5aa7ff.').setRequired(false).setMaxLength(7)).addStringOption((o)=>o.setName('display_mode').setDescription('Public panel component style.').setRequired(false).addChoices({name:'Buttons',value:'BUTTONS'},{name:'Dropdown menu',value:'DROPDOWN'})))
  .addSubcommand((s)=>s.setName('panel').setDescription('Post a public appeal launcher panel.').addChannelOption((o)=>o.setName('channel').setDescription('Channel to post the panel in. Defaults to current channel.').addChannelTypes(ChannelType.GuildText).setRequired(false)))
  .addSubcommand((s)=>s.setName('submit').setDescription('Submit an appeal.').addStringOption((o)=>o.setName('reason').setDescription('Why should staff review this?').setRequired(true).setMaxLength(1000)).addIntegerOption((o)=>o.setName('case_number').setDescription('Case number if known.').setRequired(false).setMinValue(1)).addStringOption((o)=>o.setName('details').setDescription('Additional context.').setRequired(false).setMaxLength(1000))), actionKey:ActionKeys.AppealsPanel,moduleKey:ModuleKeys.APPEALS,
  getActionKey(i){const s=i.options.getSubcommand();if(s==='setup')return ActionKeys.AppealsConfigure;if(s==='manager')return ActionKeys.AppealsManager;if(s==='panel')return ActionKeys.AppealsPostPanel;if(s==='submit')return ActionKeys.AppealsSubmit;return ActionKeys.AppealsReview;}, isPublic(i){return i.options.getSubcommand()==='submit';},
  async execute(i,ctx){const s=i.options.getSubcommand();await ctx.permissions.ensureGuildConfig(i.guildId,i.guild?.name||null);if(s==='manager')return replyPrivate(i,await buildAppealsPanel(i.guildId));if(s==='setup'){const c=i.options.getChannel('review_channel',true);const cfg=await appeals.updateConfig(i.guildId,{reviewChannelId:c.id,dmDecisionEnabled:i.options.getBoolean('dm_decision')||false,dmIncludeSubmission:i.options.getBoolean('dm_include_submission')||false,panelTitle:i.options.getString('panel_title')||null,panelDescription:i.options.getString('panel_description')||null,panelColor:i.options.getString('panel_color')||null,panelDisplayMode:i.options.getString('display_mode')||null});const r=await refreshPublishedPanel(ctx.client,i.guildId,'appeal','*').catch(()=>null);return replyPrivate(i,{embeds:[createSuccessEmbed('Appeal System Configured',[`Review Channel: <#${c.id}>`,`DM Decisions: **${cfg.dm_decision_enabled?'Enabled':'Disabled'}**`,`Include Submission in DM: **${cfg.dm_include_submission?'Enabled':'Disabled'}**`,formatRefreshSummary(r)].filter(Boolean).join('\n'))]});}if(s==='panel'){const c=i.options.getChannel('channel')||i.channel;const m=await c.send(buildPublicAppealPanel(await appeals.getConfig(i.guildId)));await recordPublishedPanel({guildId:i.guildId,panelType:'appeal',panelRef:'*',channelId:c.id,messageId:m.id});return replyPrivate(i,{embeds:[createSuccessEmbed('Appeal Panel Posted',`Panel posted in <#${c.id}>. Future appeal panel edits will update this message automatically.`)]});}const a=await appeals.submitAppeal({interaction:i,client:ctx.client,logger:ctx.logger,caseNumber:i.options.getInteger('case_number')||null,reason:i.options.getString('reason',true),details:i.options.getString('details')||null});return replyPrivate(i,{embeds:[createSuccessEmbed('Appeal Submitted',`Appeal #${a.appeal_number} was sent to staff.`)]});}
};
