const { ChannelType, SlashCommandBuilder } = require('discord.js');
const { ModuleKeys } = require('../modules/moduleRegistry');
const { ActionKeys } = require('../modules/permissions/actionKeys');
const { replyPrivate } = require('../utils/reply');
const { ApplicationService } = require('../modules/support/supportService');
const { buildApplicationsPanel, buildPublicApplicationPanel } = require('../modules/support/supportUi');
const { createBaseEmbed, createSuccessEmbed, createWarningEmbed, SlickBotColors } = require('../modules/ui/uiService');
const { recordPublishedPanel } = require('../modules/panels/publishedPanelService');
const { refreshPublishedPanel, formatRefreshSummary } = require('../modules/panels/panelUpdateService');
const applications=new ApplicationService();
module.exports={
 data:new SlashCommandBuilder().setName('application').setDescription('Application system tools.')
 .addSubcommand(s=>s.setName('manager').setDescription('Open the application manager panel.'))
 .addSubcommand(s=>s.setName('setup').setDescription('Create or update an application type.').addStringOption(o=>o.setName('type').setDescription('Application type name.').setRequired(true).setMaxLength(80)).addChannelOption(o=>o.setName('review_channel').setDescription('Private staff review channel.').addChannelTypes(ChannelType.GuildText).setRequired(true)).addRoleOption(o=>o.setName('pending_role').setDescription('Role assigned while pending.').setRequired(false)).addRoleOption(o=>o.setName('approved_role').setDescription('Role assigned when approved.').setRequired(false)).addBooleanOption(o=>o.setName('auto_assign').setDescription('Automatically assign approved role.').setRequired(false)).addStringOption(o=>o.setName('description').setDescription('Panel/application description.').setRequired(false).setMaxLength(500)).addStringOption(o=>o.setName('confirmation_message').setDescription('DM message after user submits. Use {number} and {type}.').setRequired(false).setMaxLength(800)).addStringOption(o=>o.setName('panel_title').setDescription('Public application panel title.').setRequired(false).setMaxLength(100)).addStringOption(o=>o.setName('panel_description').setDescription('Public application panel description.').setRequired(false).setMaxLength(800)).addStringOption(o=>o.setName('panel_color').setDescription('Panel accent color, example: #7869ff.').setRequired(false).setMaxLength(7)).addStringOption(o=>o.setName('display_mode').setDescription('Public panel component style.').setRequired(false).addChoices({name:'Buttons',value:'BUTTONS'},{name:'Dropdown menu',value:'DROPDOWN'})))
 .addSubcommand(s=>s.setName('question-add').setDescription('Add a custom DM question to an application type.').addStringOption(o=>o.setName('type').setDescription('Application type name.').setRequired(true).setMaxLength(80)).addStringOption(o=>o.setName('question').setDescription('Question text.').setRequired(true).setMaxLength(300)).addBooleanOption(o=>o.setName('required').setDescription('Whether this question is required.').setRequired(false)).addIntegerOption(o=>o.setName('order').setDescription('Display order.').setMinValue(1).setMaxValue(50).setRequired(false)))
 .addSubcommand(s=>s.setName('question-list').setDescription('List custom questions for an application type.').addStringOption(o=>o.setName('type').setDescription('Application type name.').setRequired(true).setMaxLength(80)))
 .addSubcommand(s=>s.setName('question-clear').setDescription('Clear all custom questions for an application type.').addStringOption(o=>o.setName('type').setDescription('Application type name.').setRequired(true).setMaxLength(80)))
 .addSubcommand(s=>s.setName('delete').setDescription('Delete an application type template and related data.').addStringOption(o=>o.setName('type').setDescription('Application type name.').setRequired(true).setMaxLength(80)).addBooleanOption(o=>o.setName('confirm').setDescription('Must be true to delete the application type.').setRequired(true)))
 .addSubcommand(s=>s.setName('panel').setDescription('Post a public application panel.').addStringOption(o=>o.setName('type').setDescription('Application type name.').setRequired(true).setMaxLength(80)).addChannelOption(o=>o.setName('channel').setDescription('Channel to post the panel in.').addChannelTypes(ChannelType.GuildText).setRequired(false)))
 .addSubcommand(s=>s.setName('apply').setDescription('Start a DM-based application.').addStringOption(o=>o.setName('type').setDescription('Application type name.').setRequired(true).setMaxLength(80))),
 actionKey:ActionKeys.ApplicationsPanel,moduleKey:ModuleKeys.APPLICATIONS,
 getActionKey(i){const s=i.options.getSubcommand();if(['setup','delete','question-add','question-clear'].includes(s))return ActionKeys.ApplicationsConfigure;if(['manager','question-list'].includes(s))return ActionKeys.ApplicationsManager;if(s==='panel')return ActionKeys.ApplicationsPostPanel;if(s==='apply')return ActionKeys.ApplicationsApply;return ActionKeys.ApplicationsReview;},
 isPublic(i){return i.options.getSubcommand()==='apply';},
 async execute(interaction,ctx){const sub=interaction.options.getSubcommand();await ctx.permissions.ensureGuildConfig(interaction.guildId,interaction.guild?.name||null);await applications.ensureDefaultType(interaction.guildId);if(sub==='manager')return replyPrivate(interaction,await buildApplicationsPanel(interaction.guildId));
 if(sub==='setup'){const type=await applications.setupType(interaction.guildId,{name:interaction.options.getString('type',true),reviewChannelId:interaction.options.getChannel('review_channel',true).id,pendingRoleId:interaction.options.getRole('pending_role')?.id||null,approvedRoleId:interaction.options.getRole('approved_role')?.id||null,autoAssignApprovedRole:interaction.options.getBoolean('auto_assign')||false,description:interaction.options.getString('description')||null,submissionConfirmationMessage:interaction.options.getString('confirmation_message')||null,panelTitle:interaction.options.getString('panel_title')||null,panelDescription:interaction.options.getString('panel_description')||null,panelColor:interaction.options.getString('panel_color')||null,panelDisplayMode:interaction.options.getString('display_mode')||null});await ctx.logger.log({guildId:interaction.guildId,eventKey:'setup',title:'Application Settings Updated',body:`${type.name} application settings updated by ${interaction.user.tag}.`,actorUserId:interaction.user.id}).catch(()=>{});const r=await refreshPublishedPanel(ctx.client,interaction.guildId,'application',type.id).catch(()=>null);return replyPrivate(interaction,{embeds:[createSuccessEmbed('Application Type Configured',`Application type **${type.name}** is ready. Use \`/application question-add\` to customize the DM questions.${formatRefreshSummary(r)}`)]});}
 if(sub==='delete'){const name=interaction.options.getString('type',true);if(!interaction.options.getBoolean('confirm',true))return replyPrivate(interaction,{embeds:[createWarningEmbed('Delete Not Confirmed','Run the command again with `confirm:true`.')]});const result=await applications.deleteType(interaction.guildId,name);if(!result.ok)return replyPrivate(interaction,{embeds:[createWarningEmbed('Application Type Not Deleted',result.reason)]});const r=await refreshPublishedPanel(ctx.client,interaction.guildId,'application',result.type.id).catch(()=>null);return replyPrivate(interaction,{embeds:[createSuccessEmbed('Application Type Deleted',`Deleted **${result.type.name}**.${formatRefreshSummary(r)}`)]});}
 if(sub==='question-add'){const q=await applications.addQuestion(interaction.guildId,interaction.options.getString('type',true),interaction.options.getString('question',true),interaction.options.getBoolean('required')??true,interaction.options.getInteger('order')||null);if(!q)return replyPrivate(interaction,{embeds:[createWarningEmbed('Application Type Not Found','Create it with `/application setup` first.')]});return replyPrivate(interaction,{embeds:[createSuccessEmbed('Application Question Added',`Question added at order **${q.display_order}**.`)]});}
 if(sub==='question-list'){const type=await applications.getTypeByName(interaction.guildId,interaction.options.getString('type',true));if(!type)return replyPrivate(interaction,{embeds:[createWarningEmbed('Application Type Not Found','That application type could not be found.')]});const qs=await applications.getQuestions(type.id);return replyPrivate(interaction,{embeds:[createBaseEmbed({title:`${type.name} Questions`,description:qs.length?qs.map((q,i)=>`${i+1}. ${q.required?'**Required**':'Optional'} — ${q.question_text}`).join('\n'):'No questions configured.',color:SlickBotColors.INFO})]});}
 if(sub==='question-clear'){const type=await applications.clearQuestions(interaction.guildId,interaction.options.getString('type',true));if(!type)return replyPrivate(interaction,{embeds:[createWarningEmbed('Application Type Not Found','That application type could not be found.')]});return replyPrivate(interaction,{embeds:[createSuccessEmbed('Application Questions Cleared',`Questions cleared for **${type.name}**.`)]});}
 if(sub==='panel'){const type=await applications.getTypeByName(interaction.guildId,interaction.options.getString('type',true));if(!type)return replyPrivate(interaction,{embeds:[createWarningEmbed('Application Type Not Found','Create it first.')]});const channel=interaction.options.getChannel('channel')||interaction.channel;const message=await channel.send(buildPublicApplicationPanel(type));await recordPublishedPanel({guildId:interaction.guildId,panelType:'application',panelRef:type.id,channelId:channel.id,messageId:message.id});return replyPrivate(interaction,{embeds:[createSuccessEmbed('Application Panel Posted',`Panel posted in <#${channel.id}>.`)]});}
 if(sub==='apply'){const type=await applications.getTypeByName(interaction.guildId,interaction.options.getString('type',true));if(!type||!type.enabled)return replyPrivate(interaction,{embeds:[createWarningEmbed('Application Unavailable','This application type is not available.')]});const result=await applications.startApplicationDm({interaction,client:ctx.client,logger:ctx.logger,applicationType:type});if(!result.ok)return replyPrivate(interaction,{embeds:[createWarningEmbed('Application Not Started',result.reason)]});return replyPrivate(interaction,{embeds:[createSuccessEmbed('Application Started',`I sent you a DM. Question count: **${result.questionCount}**.`)]});}
 }};
