const { ChannelType, SlashCommandBuilder } = require('discord.js');
const { ModuleKeys } = require('../modules/moduleRegistry');
const { ActionKeys } = require('../modules/permissions/actionKeys');
const { replyPrivate } = require('../utils/reply');
const { GiveawayService } = require('../modules/community/giveawayService');
const { createSuccessEmbed, createWarningEmbed } = require('../modules/ui/uiService');
const giveaways = new GiveawayService();
module.exports = {
  data: new SlashCommandBuilder().setName('giveaway').setDescription('Create and manage SlickBot giveaways.')
    .addSubcommand((s)=>s.setName('manager').setDescription('Open the giveaway manager panel.'))
    .addSubcommand((s)=>s.setName('setup').setDescription('Configure giveaway defaults.').addChannelOption((o)=>o.setName('default_channel').setDescription('Default channel for giveaways.').addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setRequired(false)).addRoleOption((o)=>o.setName('ping_role').setDescription('Optional role to ping when giveaways start.').setRequired(false)).addRoleOption((o)=>o.setName('host_role').setDescription('Optional host role for your records.').setRequired(false)).addStringOption((o)=>o.setName('panel_color').setDescription('Giveaway embed accent color, such as #7869ff.').setRequired(false).setMaxLength(7)))
    .addSubcommand((s)=>s.setName('start').setDescription('Start a giveaway.').addStringOption((o)=>o.setName('prize').setDescription('Giveaway prize.').setRequired(true).setMaxLength(200)).addStringOption((o)=>o.setName('duration').setDescription('Duration, such as 30m, 2h, or 1d.').setRequired(true).setMaxLength(20)).addIntegerOption((o)=>o.setName('winners').setDescription('Number of winners.').setMinValue(1).setMaxValue(20).setRequired(false)).addChannelOption((o)=>o.setName('channel').setDescription('Channel to post the giveaway. Defaults to configured channel/current channel.').addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setRequired(false)).addStringOption((o)=>o.setName('description').setDescription('Optional giveaway details.').setRequired(false).setMaxLength(1000)))
    .addSubcommand((s)=>s.setName('end').setDescription('End a giveaway early and pick winners.').addIntegerOption((o)=>o.setName('number').setDescription('Giveaway number.').setRequired(true).setMinValue(1)))
    .addSubcommand((s)=>s.setName('reroll').setDescription('Reroll winners for a giveaway.').addIntegerOption((o)=>o.setName('number').setDescription('Giveaway number.').setRequired(true).setMinValue(1)))
    .addSubcommand((s)=>s.setName('list').setDescription('List active giveaways.')),
  moduleKey:ModuleKeys.GIVEAWAYS,
  getActionKey(i){const s=i.options.getSubcommand();if(['manager','list'].includes(s))return ActionKeys.GiveawaysView;if(s==='start')return ActionKeys.GiveawaysCreate;if(s==='end')return ActionKeys.GiveawaysEnd;if(s==='reroll')return ActionKeys.GiveawaysReroll;return ActionKeys.GiveawaysConfigure;},
  async execute(i,ctx){const s=i.options.getSubcommand();await ctx.permissions.ensureGuildConfig(i.guildId,i.guild?.name||null);if(['manager','list'].includes(s))return replyPrivate(i,await giveaways.buildManagerPanel(i.guildId));if(s==='setup'){const c=await giveaways.updateConfig(i.guildId,{defaultChannelId:i.options.getChannel('default_channel')?.id||null,pingRoleId:i.options.getRole('ping_role')?.id||null,hostRoleId:i.options.getRole('host_role')?.id||null,panelColor:i.options.getString('panel_color')||null});await ctx.logger.log({guildId:i.guildId,eventKey:'giveaway-config',title:'Giveaway Settings Updated',body:`Giveaway settings updated by <@${i.user.id}>.`,actorUserId:i.user.id}).catch(()=>{});return replyPrivate(i,{embeds:[createSuccessEmbed('Giveaway Settings Saved',[`Default Channel: ${c.default_channel_id?`<#${c.default_channel_id}>`:'Not set'}`,`Ping Role: ${c.ping_role_id?`<@&${c.ping_role_id}>`:'Not set'}`].join('\n'))]});}if(s==='start'){const r=await giveaways.startGiveaway({interaction:i,client:ctx.client,logger:ctx.logger,channel:i.options.getChannel('channel')||null,prize:i.options.getString('prize',true),description:i.options.getString('description')||null,duration:i.options.getString('duration',true),winnerCount:i.options.getInteger('winners')||1});if(!r.ok)return replyPrivate(i,{embeds:[createWarningEmbed('Giveaway Not Started',r.reason)]});return replyPrivate(i,{embeds:[createSuccessEmbed('Giveaway Started',`Giveaway #${r.giveaway.giveaway_number} was posted in <#${r.channel.id}>.`)]});}const reroll=s==='reroll';const r=await giveaways.endGiveaway({client:ctx.client,guildId:i.guildId,giveawayNumber:i.options.getInteger('number',true),actorUserId:i.user.id,logger:ctx.logger,reroll});if(!r.ok)return replyPrivate(i,{embeds:[createWarningEmbed(reroll?'Giveaway Not Rerolled':'Giveaway Not Ended',r.reason)]});return replyPrivate(i,{embeds:[createSuccessEmbed(reroll?'Giveaway Rerolled':'Giveaway Ended',`Giveaway #${r.giveaway.giveaway_number} ${reroll?'was rerolled':'ended'}. ${reroll?'New winners':'Winners'}: **${r.winners.length}**.`)]});}
};
