const { ChannelType, SlashCommandBuilder } = require('discord.js');
const { ModuleKeys } = require('../modules/moduleRegistry');
const { ActionKeys } = require('../modules/permissions/actionKeys');
const { replyPrivate } = require('../utils/reply');
const { ReportService } = require('../modules/support/supportService');
const { buildReportsPanel, buildPublicReportPanel } = require('../modules/support/supportUi');
const { createSuccessEmbed } = require('../modules/ui/uiService');
const { recordPublishedPanel } = require('../modules/panels/publishedPanelService');
const { refreshPublishedPanel, formatRefreshSummary } = require('../modules/panels/panelUpdateService');
const reports = new ReportService();
module.exports = {
  data: new SlashCommandBuilder().setName('report').setDescription('Report system tools.')
    .addSubcommand((s) => s.setName('manager').setDescription('Open the report manager panel.'))
    .addSubcommand((s) => s.setName('setup').setDescription('Set the report review channel and optional pings.').addChannelOption((o) => o.setName('review_channel').setDescription('Private staff report review channel.').addChannelTypes(ChannelType.GuildText).setRequired(true)).addRoleOption((o) => o.setName('ping_role').setDescription('Role to ping when a report is submitted.').setRequired(false)).addStringOption((o) => o.setName('ping_team').setDescription('Permission Team to ping when a report is submitted.').setRequired(false).setMaxLength(80)).addStringOption((o) => o.setName('panel_title').setDescription('Public report panel title.').setRequired(false).setMaxLength(100)).addStringOption((o) => o.setName('panel_description').setDescription('Public report panel description.').setRequired(false).setMaxLength(800)).addStringOption((o) => o.setName('panel_color').setDescription('Panel accent color, example: #f2b84b.').setRequired(false).setMaxLength(7)).addStringOption((o) => o.setName('display_mode').setDescription('Public panel component style.').setRequired(false).addChoices({ name: 'Buttons', value: 'BUTTONS' }, { name: 'Dropdown menu', value: 'DROPDOWN' })))
    .addSubcommand((s) => s.setName('panel').setDescription('Post a public report launcher panel.').addChannelOption((o) => o.setName('channel').setDescription('Channel to post the panel in. Defaults to current channel.').addChannelTypes(ChannelType.GuildText).setRequired(false)))
    .addSubcommand((s) => s.setName('user').setDescription('Privately report a user to staff.').addUserOption((o) => o.setName('user').setDescription('User being reported.').setRequired(true)).addStringOption((o) => o.setName('details').setDescription('What happened?').setRequired(true).setMaxLength(1800)).addStringOption((o) => o.setName('message_link').setDescription('Optional Discord message link.').setRequired(false).setMaxLength(300)))
    .addSubcommand((s) => s.setName('issue').setDescription('Privately report a general issue to staff.').addStringOption((o) => o.setName('details').setDescription('What happened?').setRequired(true).setMaxLength(1800))),
  actionKey: ActionKeys.ReportsPanel, moduleKey: ModuleKeys.REPORTS,
  getActionKey(interaction) { const s = interaction.options.getSubcommand(); if (s === 'setup') return ActionKeys.ReportsConfigure; if (s === 'manager') return ActionKeys.ReportsManager; if (s === 'panel') return ActionKeys.ReportsPostPanel; if (['user','issue'].includes(s)) return ActionKeys.ReportsSubmit; return ActionKeys.ReportsReview; },
  isPublic(interaction) { return ['user','issue'].includes(interaction.options.getSubcommand()); },
  async execute(interaction, ctx) {
    const s = interaction.options.getSubcommand(); await ctx.permissions.ensureGuildConfig(interaction.guildId, interaction.guild?.name || null);
    if (s === 'manager') return replyPrivate(interaction, await buildReportsPanel(interaction.guildId));
    if (s === 'setup') { const channel = interaction.options.getChannel('review_channel', true); const config = await reports.updateConfig(interaction.guildId, { reviewChannelId: channel.id, pingRoleId: interaction.options.getRole('ping_role')?.id || null, pingTeamName: interaction.options.getString('ping_team') || null, panelTitle: interaction.options.getString('panel_title') || null, panelDescription: interaction.options.getString('panel_description') || null, panelColor: interaction.options.getString('panel_color') || null, panelDisplayMode: interaction.options.getString('display_mode') || null }); const refresh = await refreshPublishedPanel(ctx.client, interaction.guildId, 'report', '*').catch(() => null); return replyPrivate(interaction, { embeds: [createSuccessEmbed('Report System Configured', [`Review Channel: <#${channel.id}>`, `Ping Role: ${config.ping_role_id ? `<@&${config.ping_role_id}>` : 'Not set'}`, `Ping Team: ${config.ping_team_id ? 'Configured' : 'Not set'}`, formatRefreshSummary(refresh)].filter(Boolean).join('\n'))] }); }
    if (s === 'panel') { const channel = interaction.options.getChannel('channel') || interaction.channel; const message = await channel.send(buildPublicReportPanel(await reports.getConfig(interaction.guildId))); await recordPublishedPanel({ guildId: interaction.guildId, panelType: 'report', panelRef: '*', channelId: channel.id, messageId: message.id }); return replyPrivate(interaction, { embeds: [createSuccessEmbed('Report Panel Posted', `Panel posted in <#${channel.id}>. Future report panel edits will update this message automatically.`)] }); }
    const report = await reports.createReport({ interaction, client: ctx.client, logger: ctx.logger, type: s === 'user' ? 'User Report' : 'General Issue', targetUser: s === 'user' ? interaction.options.getUser('user', true) : null, details: interaction.options.getString('details', true), messageLink: interaction.options.getString('message_link') || null }); return replyPrivate(interaction, { embeds: [createSuccessEmbed('Report Submitted', `Report #${report.report_number} was sent to staff.`)] });
  }
};
