const { ChannelType, SlashCommandBuilder } = require('discord.js');
const { ModuleKeys } = require('../modules/moduleRegistry');
const { ActionKeys } = require('../modules/permissions/actionKeys');
const { replyPrivate } = require('../utils/reply');
const { createSuccessEmbed, createWarningEmbed } = require('../modules/ui/uiService');
const { ScheduledMessageService, formatTimestamp } = require('../modules/automation/scheduledMessageService');
const scheduler = new ScheduledMessageService();
module.exports={data:new SlashCommandBuilder().setName('schedule').setDescription('Create and manage scheduled SlickBot messages.')
.addSubcommand((s)=>s.setName('manager').setDescription('Open the scheduled messages manager panel.'))
.addSubcommand((s)=>s.setName('setup').setDescription('Configure scheduled message defaults.').addChannelOption((o)=>o.setName('default_channel').setDescription('Default channel for scheduled messages.').addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setRequired(false)).addBooleanOption((o)=>o.setName('enabled').setDescription('Enable or disable scheduled message sending.').setRequired(false)))
.addSubcommand((s)=>s.setName('create').setDescription('Create a scheduled message.').addStringOption((o)=>o.setName('message').setDescription('Message content to send.').setRequired(true).setMaxLength(1500)).addStringOption((o)=>o.setName('delay').setDescription('Delay before sending, such as 30m, 2h, 1d, or 1w.').setRequired(true).setMaxLength(20)).addChannelOption((o)=>o.setName('channel').setDescription('Channel to send in. Defaults to configured channel/current channel.').addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setRequired(false)).addStringOption((o)=>o.setName('repeat').setDescription('Optional repeat mode.').setRequired(false).addChoices({name:'No Repeat',value:'NONE'},{name:'Daily',value:'DAILY'},{name:'Weekly',value:'WEEKLY'})))
.addSubcommand((s)=>s.setName('list').setDescription('List upcoming scheduled messages.'))
.addSubcommand((s)=>s.setName('cancel').setDescription('Cancel a scheduled message.').addIntegerOption((o)=>o.setName('number').setDescription('Scheduled message number.').setRequired(true).setMinValue(1)))
.addSubcommand((s)=>s.setName('send-now').setDescription('Send a scheduled message now.').addIntegerOption((o)=>o.setName('number').setDescription('Scheduled message number.').setRequired(true).setMinValue(1))),moduleKey:ModuleKeys.SCHEDULED_MESSAGES,
getActionKey(i){const s=i.options.getSubcommand();if(['manager','list'].includes(s))return ActionKeys.ScheduledMessagesView;if(s==='create')return ActionKeys.ScheduledMessagesCreate;if(s==='cancel')return ActionKeys.ScheduledMessagesCancel;if(s==='send-now')return ActionKeys.ScheduledMessagesSendNow;return ActionKeys.ScheduledMessagesConfigure;},
async execute(i,ctx){const s=i.options.getSubcommand();await ctx.permissions.ensureGuildConfig(i.guildId,i.guild?.name||null);if(['manager','list'].includes(s))return replyPrivate(i,await scheduler.buildManagerPanel(i.guildId));if(s==='setup'){const c=await scheduler.updateConfig(i.guildId,{defaultChannelId:i.options.getChannel('default_channel')?.id||null,enabled:i.options.getBoolean('enabled')??true});return replyPrivate(i,{embeds:[createSuccessEmbed('Scheduled Messages Saved',`Default channel: ${c.default_channel_id?`<#${c.default_channel_id}>`:'not set'}. Module sending is **${c.enabled?'enabled':'disabled'}**.`)]});}if(s==='create'){const cfg=await scheduler.getConfig(i.guildId);const ch=i.options.getChannel('channel')||(cfg.default_channel_id?await i.guild.channels.fetch(cfg.default_channel_id).catch(()=>null):i.channel);if(!ch||typeof ch.send!=='function')return replyPrivate(i,{embeds:[createWarningEmbed('Channel Required','Choose a channel or configure a default scheduled message channel first.')]});const r=await scheduler.createScheduledMessage({guildId:i.guildId,channelId:ch.id,actorUserId:i.user.id,content:i.options.getString('message',true),delay:i.options.getString('delay',true),repeat:i.options.getString('repeat')||'NONE'});if(!r.ok)return replyPrivate(i,{embeds:[createWarningEmbed('Schedule Not Created',r.reason)]});return replyPrivate(i,{embeds:[createSuccessEmbed('Scheduled Message Created',`Schedule #${r.schedule.schedule_number} will send in <#${ch.id}> ${formatTimestamp(r.schedule.send_at)}.`)]});}if(s==='cancel'){const r=await scheduler.cancel(i.guildId,i.options.getInteger('number',true),i.user.id);if(!r)return replyPrivate(i,{embeds:[createWarningEmbed('Schedule Not Cancelled','That scheduled message was not found or is not active.')]});return replyPrivate(i,{embeds:[createSuccessEmbed('Scheduled Message Cancelled',`Schedule #${r.schedule_number} has been cancelled.`)]});}const r=await scheduler.sendNow({client:ctx.client,guildId:i.guildId,scheduleNumber:i.options.getInteger('number',true),actorUserId:i.user.id,logger:ctx.logger});if(!r.ok)return replyPrivate(i,{embeds:[createWarningEmbed('Schedule Not Sent',r.reason)]});return replyPrivate(i,{embeds:[createSuccessEmbed('Scheduled Message Sent',`Schedule #${r.schedule.schedule_number} was sent to <#${r.channel.id}>.`)]});}}
