const { SlashCommandBuilder, ChannelType } = require('discord.js');
const { ModuleKeys } = require('../modules/moduleRegistry');
const { ActionKeys } = require('../modules/permissions/actionKeys');
const { replyPrivate } = require('../utils/reply');
const { createSuccessEmbed, createWarningEmbed } = require('../modules/ui/uiService');
const welcome = require('../modules/community/welcomeService');
module.exports={data:new SlashCommandBuilder().setName('welcome').setDescription('Configure welcome messages and auto roles.')
.addSubcommand((s)=>s.setName('manager').setDescription('Open the welcome manager panel.'))
.addSubcommand((s)=>s.setName('setup').setDescription('Configure the welcome message system.').addChannelOption((o)=>o.setName('channel').setDescription('Channel where welcome messages should be sent.').addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setRequired(false)).addBooleanOption((o)=>o.setName('enabled').setDescription('Enable or disable welcome messages.').setRequired(false)).addStringOption((o)=>o.setName('message').setDescription('Optional public message content. Supports {user}, {server}, {memberCount}.').setRequired(false).setMaxLength(1000)).addStringOption((o)=>o.setName('title').setDescription('Embed title. Supports placeholders.').setRequired(false).setMaxLength(256)).addStringOption((o)=>o.setName('description').setDescription('Embed description. Supports placeholders.').setRequired(false).setMaxLength(1500)).addStringOption((o)=>o.setName('color').setDescription('Embed accent color, such as #7869ff.').setRequired(false)).addBooleanOption((o)=>o.setName('dm_enabled').setDescription('Whether to DM new members.').setRequired(false)).addStringOption((o)=>o.setName('dm_message').setDescription('DM message. Supports placeholders.').setRequired(false).setMaxLength(1000)))
.addSubcommand((s)=>s.setName('auto-role-add').setDescription('Add a role to assign when a user joins.').addRoleOption((o)=>o.setName('role').setDescription('Role to assign on join.').setRequired(true)))
.addSubcommand((s)=>s.setName('auto-role-remove').setDescription('Remove an auto role.').addRoleOption((o)=>o.setName('role').setDescription('Role to remove from auto roles.').setRequired(true)))
.addSubcommand((s)=>s.setName('auto-role-list').setDescription('List configured auto roles.')).addSubcommand((s)=>s.setName('test').setDescription('Preview the welcome message using yourself.')),moduleKey:ModuleKeys.WELCOME,
getActionKey(i){const s=i.options.getSubcommand();if(['manager','auto-role-list'].includes(s))return ActionKeys.WelcomeView;if(s==='test')return ActionKeys.WelcomeTest;return ActionKeys.WelcomeConfigure;},
async execute(i,ctx){const s=i.options.getSubcommand();if(s==='manager')return replyPrivate(i,await welcome.buildWelcomePanel(i.guildId));if(s==='setup'){const c=await welcome.upsertWelcomeConfig({guildId:i.guildId,channelId:i.options.getChannel('channel')?.id,enabled:i.options.getBoolean('enabled')??undefined,message:i.options.getString('message')??undefined,title:i.options.getString('title')??undefined,description:i.options.getString('description')??undefined,color:i.options.getString('color')??undefined,dmEnabled:i.options.getBoolean('dm_enabled')??undefined,dmMessage:i.options.getString('dm_message')??undefined});return replyPrivate(i,{embeds:[createSuccessEmbed('Welcome Updated',`Welcome channel: ${c.channel_id?`<#${c.channel_id}>`:'Not set'}\nDM welcome: **${c.dm_enabled?'Enabled':'Disabled'}**`)]});}if(s==='auto-role-add'||s==='auto-role-remove'){const r=i.options.getRole('role',true);if(s==='auto-role-add')await welcome.addAutoRole(i.guildId,r.id,i.user.id);else await welcome.removeAutoRole(i.guildId,r.id);return replyPrivate(i,{embeds:[createSuccessEmbed(s==='auto-role-add'?'Auto Role Added':'Auto Role Removed',`<@&${r.id}> ${s==='auto-role-add'?'will be assigned to new members.':'will no longer be assigned automatically.'}`)]});}if(s==='auto-role-list'){const rs=await welcome.listAutoRoles(i.guildId);return replyPrivate(i,{embeds:[createSuccessEmbed('Auto Roles',rs.length?rs.map((id)=>`• <@&${id}>`).join('\n'):'No auto roles configured.')]});}const c=await welcome.getWelcomeConfig(i.guildId);if(!c?.channel_id)return replyPrivate(i,{embeds:[createWarningEmbed('Welcome Not Configured','Set a welcome channel first with `/welcome setup`.')]});const ch=await i.guild.channels.fetch(c.channel_id).catch(()=>null);if(!ch||typeof ch.send!=='function')return replyPrivate(i,{embeds:[createWarningEmbed('Channel Unavailable','The configured welcome channel could not be used.')]});const e=require('../modules/ui/uiService').createBaseEmbed({title:welcome.applyPlaceholders(c.embed_title||'Welcome to {server}',i.member),description:welcome.applyPlaceholders(c.embed_description||'Glad to have you here, {user}.',i.member),color:welcome.parseColor(c.embed_color),footer:'SlickBot Welcome Test'});await ch.send({content:c.message_template?welcome.applyPlaceholders(c.message_template,i.member):null,embeds:[e]});return replyPrivate(i,{embeds:[createSuccessEmbed('Welcome Test Sent',`Sent a test welcome message to <#${ch.id}>.`)]});}}
