const ActionKeys = Object.freeze({
  BotPing: 'bot.ping',
  Setup: 'setup.run',
  TeamsManage: 'permissions.teams.manage',
  ModulesManage: 'permissions.modules.manage',
  LoggingConfigure: 'logging.configure',
  LoggingView: 'logging.view',
  StatusView: 'status.view',
  StatusManage: 'status.manage',

  ModerationPanel: 'moderation.panel',
  ModerationWarn: 'moderation.warn',
  ModerationTimeout: 'moderation.timeout',
  ModerationKick: 'moderation.kick',
  ModerationBan: 'moderation.ban',
  ModerationMassBan: 'moderation.massban',
  CasesView: 'cases.view',
  CasesManage: 'cases.manage',
  UserNotesView: 'user-notes.view',
  UserNotesManage: 'user-notes.manage',

  TicketsConfigure: 'tickets.configure',
  TicketsPanel: 'tickets.panel',
  TicketsManage: 'tickets.manage',
  TicketsClaim: 'tickets.claim',
  TicketsClose: 'tickets.close',

  ReportsConfigure: 'reports.configure',
  ReportsPanel: 'reports.panel',
  ReportsReview: 'reports.review',

  ApplicationsConfigure: 'applications.configure',
  ApplicationsPanel: 'applications.panel',
  ApplicationsReview: 'applications.review',
  ApplicationsApprove: 'applications.approve',
  ApplicationsDeny: 'applications.deny',

  AppealsConfigure: 'appeals.configure',
  AppealsPanel: 'appeals.panel',
  AppealsReview: 'appeals.review',
  AppealsApprove: 'appeals.approve',
  AppealsDeny: 'appeals.deny'
});

const defaultTeamPermissions = [
  ActionKeys.BotPing,
  ActionKeys.Setup,
  ActionKeys.TeamsManage,
  ActionKeys.ModulesManage,
  ActionKeys.LoggingConfigure,
  ActionKeys.LoggingView,
  ActionKeys.StatusView,
  ActionKeys.StatusManage,
  ActionKeys.ModerationPanel,
  ActionKeys.ModerationWarn,
  ActionKeys.ModerationTimeout,
  ActionKeys.ModerationKick,
  ActionKeys.ModerationBan,
  ActionKeys.ModerationMassBan,
  ActionKeys.CasesView,
  ActionKeys.CasesManage,
  ActionKeys.UserNotesView,
  ActionKeys.UserNotesManage,
  ActionKeys.TicketsConfigure,
  ActionKeys.TicketsPanel,
  ActionKeys.TicketsManage,
  ActionKeys.TicketsClaim,
  ActionKeys.TicketsClose,
  ActionKeys.ReportsConfigure,
  ActionKeys.ReportsPanel,
  ActionKeys.ReportsReview,
  ActionKeys.ApplicationsConfigure,
  ActionKeys.ApplicationsPanel,
  ActionKeys.ApplicationsReview,
  ActionKeys.ApplicationsApprove,
  ActionKeys.ApplicationsDeny,
  ActionKeys.AppealsConfigure,
  ActionKeys.AppealsPanel,
  ActionKeys.AppealsReview,
  ActionKeys.AppealsApprove,
  ActionKeys.AppealsDeny
];

module.exports = {
  ActionKeys,
  defaultTeamPermissions
};
