const { createBaseEmbed, createButtonRow, createPanelButton, ButtonStyle, SlickBotColors } = require('../ui/uiService');
const { CustomIds } = require('../ui/customIds');
const { query } = require('../../services/db');
const { formatCaseLine } = require('./moderationService');
function buildCaseEmbed(c){return createBaseEmbed({title:`Moderation Case #${c.case_number}`,description:[`Action: **${c.action_type}**`,`Target: <@${c.target_user_id}>`,`Actor: ${c.actor_user_id?`<@${c.actor_user_id}>`:'System'}`,`Status: **${c.status}**`,`Reason: ${c.reason||'No reason provided.'}`,c.expires_at?`Expires: <t:${Math.floor(new Date(c.expires_at).getTime()/1000)}:F>`:null].filter(Boolean).join('\n'),color:SlickBotColors.INFO,footer:'SlickBot Moderation'});}
function buildNotesEmbed(user,notes){return createBaseEmbed({title:`Notes • ${user.tag}`,description:notes.length?notes.map(n=>`**#${n.note_number}** by <@${n.actor_user_id}>\n${n.note}`).join('\n\n'):'No active notes.',color:notes.length?SlickBotColors.INFO:SlickBotColors.WARNING});}
async function buildRecentCasesPanel(g){const rows=(await query('SELECT * FROM moderation_cases WHERE guild_id=$1 ORDER BY case_number DESC LIMIT 15',[g])).rows;return{embeds:[createBaseEmbed({title:'Recent Moderation Cases',description:rows.length?rows.map(formatCaseLine).join('\n'):'No moderation cases.',color:rows.length?SlickBotColors.INFO:SlickBotColors.WARNING})],components:[createButtonRow([createPanelButton(CustomIds.CasesRefresh,'Refresh',ButtonStyle.Secondary,'🔄')])]};}
async function buildModerationPanel(g){const count=(await query('SELECT COUNT(*)::int count FROM moderation_cases WHERE guild_id=$1',[g])).rows[0].count;return{embeds:[createBaseEmbed({title:'Moderation Center',description:`Total Cases: **${count}**\nUse \`/mod\`, \`/case\`, and \`/note\` for moderation workflows.`,color:SlickBotColors.PRIMARY})],components:[createButtonRow([createPanelButton(CustomIds.CasesRefresh,'Recent Cases',ButtonStyle.Primary,'📚'),createPanelButton(CustomIds.SetupRefresh,'Back',ButtonStyle.Secondary,'↩️')])]};}
module.exports={buildCaseEmbed,buildNotesEmbed,buildRecentCasesPanel,buildModerationPanel};
