const { query } = require('../../services/db');
function formatCaseLine(c){return `#${c.case_number} **${c.action_type}** <@${c.target_user_id}> — ${c.reason||'No reason'} · ${c.status}`;}
class ModerationService{
 async nextCase(g){return Number((await query('SELECT COALESCE(MAX(case_number),0)+1 n FROM moderation_cases WHERE guild_id=$1',[g])).rows[0].n);}
 async createCase(i){const n=await this.nextCase(i.guildId);return(await query(`INSERT INTO moderation_cases(guild_id,case_number,target_user_id,target_user_tag,actor_user_id,action_type,reason,status,duration_seconds,expires_at,evidence,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) RETURNING *`,[i.guildId,n,i.targetUser.id,i.targetUser.tag,i.actorUser?.id||null,i.actionType,i.reason||null,i.status||'OPEN',i.durationSeconds||null,i.expiresAt||null,i.evidence||null,JSON.stringify(i.metadata||{})])).rows[0];}
 async getCase(g,n){return(await query('SELECT * FROM moderation_cases WHERE guild_id=$1 AND case_number=$2 LIMIT 1',[g,n])).rows[0]||null;}
 async listCases(g,limit=15){return(await query('SELECT * FROM moderation_cases WHERE guild_id=$1 ORDER BY case_number DESC LIMIT $2',[g,limit])).rows;}
 async updateCaseReason(g,n,reason){return(await query('UPDATE moderation_cases SET reason=$1,updated_at=NOW() WHERE guild_id=$2 AND case_number=$3 RETURNING *',[reason,g,n])).rows[0]||null;}
 async closeCase(g,n){return(await query(`UPDATE moderation_cases SET status='CLOSED',updated_at=NOW() WHERE guild_id=$1 AND case_number=$2 RETURNING *`,[g,n])).rows[0]||null;}
 async addNote({guildId,targetUser,actorUser,note}){const n=Number((await query('SELECT COALESCE(MAX(note_number),0)+1 n FROM user_notes WHERE guild_id=$1',[guildId])).rows[0].n);return(await query(`INSERT INTO user_notes(guild_id,note_number,target_user_id,target_user_tag,actor_user_id,note,is_active) VALUES($1,$2,$3,$4,$5,$6,true) RETURNING *`,[guildId,n,targetUser.id,targetUser.tag,actorUser.id,note])).rows[0];}
 async listNotes(g,u){return(await query(`SELECT * FROM user_notes WHERE guild_id=$1 AND target_user_id=$2 AND is_active=true ORDER BY note_number DESC LIMIT 25`,[g,u])).rows;}
 async removeNote(g,n){return(await query(`UPDATE user_notes SET is_active=false,updated_at=NOW() WHERE guild_id=$1 AND note_number=$2 RETURNING *`,[g,n])).rows[0]||null;}
 async warn({interaction,target,reason,logger}){const c=await this.createCase({guildId:interaction.guildId,targetUser:target,actorUser:interaction.user,actionType:'WARN',reason});await target.send?.(`You were warned in **${interaction.guild.name}**. Reason: ${reason}`).catch(()=>{});await logger?.log({guildId:interaction.guildId,eventKey:'moderation',title:'Member Warned',body:`Target: <@${target.id}>\nReason: ${reason}`,actorUserId:interaction.user.id}).catch(()=>{});return c;}
 async timeout({interaction,member,durationMs,reason,logger}){await member.timeout(durationMs,reason);const c=await this.createCase({guildId:interaction.guildId,targetUser:member.user,actorUser:interaction.user,actionType:'TIMEOUT',reason,durationSeconds:Math.floor(durationMs/1000),expiresAt:new Date(Date.now()+durationMs)});await logger?.log({guildId:interaction.guildId,eventKey:'moderation',title:'Member Timed Out',body:`Target: <@${member.id}>\nReason: ${reason}`,actorUserId:interaction.user.id}).catch(()=>{});return c;}
 async untimeout({interaction,member,reason,logger}){await member.timeout(null,reason);return this.createCase({guildId:interaction.guildId,targetUser:member.user,actorUser:interaction.user,actionType:'UNTIMEOUT',reason,status:'CLOSED'});}
 async kick({interaction,member,reason}){const user=member.user;await member.kick(reason);return this.createCase({guildId:interaction.guildId,targetUser:user,actorUser:interaction.user,actionType:'KICK',reason,status:'CLOSED'});}
 async ban({interaction,user,reason}){await interaction.guild.members.ban(user,{reason});return this.createCase({guildId:interaction.guildId,targetUser:user,actorUser:interaction.user,actionType:'BAN',reason});}
 async unban({interaction,userId,reason}){const u=await interaction.client.users.fetch(userId);await interaction.guild.members.unban(userId,reason);return this.createCase({guildId:interaction.guildId,targetUser:u,actorUser:interaction.user,actionType:'UNBAN',reason,status:'CLOSED'});}
}
module.exports={ModerationService,formatCaseLine};
