const { query } = require('../../services/db');
const { createBaseEmbed, SlickBotColors } = require('../ui/uiService');
function parseDelay(v){const m=String(v||'').trim().match(/^(\d+)\s*([mhdw])$/i);return m?Number(m[1])*({m:60000,h:3600000,d:86400000,w:604800000}[m[2].toLowerCase()]):null;}
function formatTimestamp(d){return `<t:${Math.floor(new Date(d).getTime()/1000)}:F>`;}
class ScheduledMessageService{
 async getConfig(g){const r=await query('SELECT * FROM scheduled_message_configs WHERE guild_id=$1 LIMIT 1',[g]);return r.rows[0]||{};}
 async updateConfig(g,i){const r=await query(`INSERT INTO scheduled_message_configs(guild_id,default_channel_id,enabled) VALUES($1,$2,$3) ON CONFLICT(guild_id) DO UPDATE SET default_channel_id=COALESCE(EXCLUDED.default_channel_id,scheduled_message_configs.default_channel_id),enabled=EXCLUDED.enabled,updated_at=NOW() RETURNING *`,[g,i.defaultChannelId||null,i.enabled??true]);return r.rows[0];}
 async createScheduledMessage({guildId,channelId,actorUserId,content,delay,repeat}){const ms=parseDelay(delay);if(!ms)return{ok:false,reason:'Use a delay such as `30m`, `2h`, `1d`, or `1w`.'};const n=(await query('SELECT COALESCE(MAX(schedule_number),0)+1 n FROM scheduled_messages WHERE guild_id=$1',[guildId])).rows[0].n;const r=await query(`INSERT INTO scheduled_messages(guild_id,schedule_number,channel_id,created_by_user_id,content,send_at,repeat_mode,status) VALUES($1,$2,$3,$4,$5,$6,$7,'SCHEDULED') RETURNING *`,[guildId,n,channelId,actorUserId,content,new Date(Date.now()+ms),repeat||'NONE']);return{ok:true,schedule:r.rows[0]};}
 async cancel(g,n,u){return (await query(`UPDATE scheduled_messages SET status='CANCELLED',cancelled_by_user_id=$1,updated_at=NOW() WHERE guild_id=$2 AND schedule_number=$3 AND status='SCHEDULED' RETURNING *`,[u,g,n])).rows[0]||null;}
 async sendNow({client,guildId,scheduleNumber,actorUserId,logger}){const s=(await query(`SELECT * FROM scheduled_messages WHERE guild_id=$1 AND schedule_number=$2 AND status='SCHEDULED'`,[guildId,scheduleNumber])).rows[0];if(!s)return{ok:false,reason:'Scheduled message not found.'};const ch=await client.channels.fetch(s.channel_id).catch(()=>null);if(!ch?.send)return{ok:false,reason:'The configured channel is unavailable.'};await ch.send(s.content);await this.markSent(s);await logger?.log({guildId,eventKey:'scheduled-messages',title:'Scheduled Message Sent',body:`Schedule #${s.schedule_number}`,actorUserId}).catch(()=>{});return{ok:true,schedule:s,channel:ch};}
 async markSent(s){if(s.repeat_mode==='DAILY'||s.repeat_mode==='WEEKLY'){const ms=s.repeat_mode==='DAILY'?86400000:604800000;await query(`UPDATE scheduled_messages SET send_at=$1,last_sent_at=NOW(),updated_at=NOW() WHERE id=$2`,[new Date(Date.now()+ms),s.id]);}else await query(`UPDATE scheduled_messages SET status='SENT',last_sent_at=NOW(),updated_at=NOW() WHERE id=$1`,[s.id]);}
 async processDue(client,logger){const rows=(await query(`SELECT * FROM scheduled_messages WHERE status='SCHEDULED' AND send_at<=NOW() ORDER BY send_at LIMIT 50`)).rows;for(const s of rows){const ch=await client.channels.fetch(s.channel_id).catch(()=>null);if(ch?.send){await ch.send(s.content).catch(()=>{});await this.markSent(s);await logger?.log({guildId:s.guild_id,eventKey:'scheduled-messages',title:'Scheduled Message Sent',body:`Schedule #${s.schedule_number}`}).catch(()=>{});}}return rows.length;}
 async buildManagerPanel(g){const [c,rows]=await Promise.all([this.getConfig(g),query(`SELECT * FROM scheduled_messages WHERE guild_id=$1 AND status='SCHEDULED' ORDER BY send_at LIMIT 15`,[g])]);return{embeds:[createBaseEmbed({title:'Scheduled Messages',description:[`Status: **${c.enabled===false?'Disabled':'Enabled'}**`,`Default Channel: ${c.default_channel_id?`<#${c.default_channel_id}>`:'Not set'}`,`Upcoming: **${rows.rowCount}**`,rows.rowCount?rows.rows.map(s=>`• #${s.schedule_number} → <#${s.channel_id}> ${formatTimestamp(s.send_at)}`).join('\n'):'No upcoming scheduled messages.'].join('\n'),color:c.default_channel_id?SlickBotColors.PRIMARY:SlickBotColors.WARNING})]};}
}
module.exports={ScheduledMessageService,formatTimestamp,parseDelay};
