const { query } = require('../../services/db');
const { createBaseEmbed, createWarningEmbed, createButtonRow, createPanelButton, ButtonStyle, SlickBotColors } = require('../ui/uiService');
const { CustomIds } = require('../ui/customIds');
const MONTH_NAMES=['','January','February','March','April','May','June','July','August','September','October','November','December'];
function validDate(m,d){if(!Number.isInteger(m)||m<1||m>12||!Number.isInteger(d)||d<1)return false;return d<=new Date(2024,m,0).getDate();}
function formatBirthday(m,d){return `${MONTH_NAMES[Number(m)]||m} ${Number(d)}`;}
function timezoneChoicesForAutocomplete(value){const q=String(value||'').toLowerCase();const common=['America/New_York','America/Chicago','America/Denver','America/Los_Angeles','UTC','Europe/London','Australia/Sydney'];return common.filter(x=>!q||x.toLowerCase().includes(q)).slice(0,25).map(x=>({name:x,value:x}));}
function birthdaySavedEmbed(p){return createBaseEmbed({title:'Birthday Saved',description:`Your birthday is set to **${formatBirthday(p.birth_month,p.birth_day)}**${p.timezone?` · ${p.timezone}`:''}.`,color:SlickBotColors.SUCCESS});}
function birthdayNotFoundEmbed(){return createWarningEmbed('Birthday Not Found','No birthday is saved for that user.');}
class BirthdayService{
 async getConfig(g){const r=await query('SELECT * FROM birthday_configs WHERE guild_id=$1 LIMIT 1',[g]);return r.rows[0]||null;}
 async updateConfig(g,i){const old=await this.getConfig(g)||{};const r=await query(`INSERT INTO birthday_configs(guild_id,channel_id,birthday_role_id,announcement_template,timezone,enabled) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(guild_id) DO UPDATE SET channel_id=COALESCE(EXCLUDED.channel_id,birthday_configs.channel_id),birthday_role_id=COALESCE(EXCLUDED.birthday_role_id,birthday_configs.birthday_role_id),announcement_template=COALESCE(EXCLUDED.announcement_template,birthday_configs.announcement_template),timezone=COALESCE(EXCLUDED.timezone,birthday_configs.timezone),enabled=EXCLUDED.enabled,updated_at=NOW() RETURNING *`,[g,i.channelId||null,i.birthdayRoleId||null,i.announcementTemplate||null,i.timezone||old.timezone||'America/New_York',i.enabled??old.enabled??true]);return r.rows[0];}
 async setBirthday({guildId,user,month,day,timezone}){if(!validDate(month,day))return{ok:false,reason:'Enter a valid month and day.'};const r=await query(`INSERT INTO birthday_profiles(guild_id,user_id,user_tag,birth_month,birth_day,timezone,active) VALUES($1,$2,$3,$4,$5,$6,true) ON CONFLICT(guild_id,user_id) DO UPDATE SET user_tag=EXCLUDED.user_tag,birth_month=EXCLUDED.birth_month,birth_day=EXCLUDED.birth_day,timezone=EXCLUDED.timezone,active=true,updated_at=NOW() RETURNING *`,[guildId,user.id,user.tag,month,day,timezone||null]);return{ok:true,profile:r.rows[0]};}
 async getBirthday(g,u){const r=await query(`SELECT * FROM birthday_profiles WHERE guild_id=$1 AND user_id=$2 AND active=true LIMIT 1`,[g,u]);return r.rows[0]||null;}
 async removeBirthday(g,u){const r=await query(`UPDATE birthday_profiles SET active=false,updated_at=NOW() WHERE guild_id=$1 AND user_id=$2 AND active=true RETURNING *`,[g,u]);return r.rows[0]||null;}
 async listBirthdays(g){return (await query(`SELECT * FROM birthday_profiles WHERE guild_id=$1 AND active=true ORDER BY birth_month,birth_day`,[g])).rows;}
 async buildPublicPanel(guildId){return{embeds:[createBaseEmbed({title:'Set Your Birthday',description:'Use `/birthday set` to save your birthday and receive server birthday announcements.',color:SlickBotColors.PRIMARY,footer:'SlickBot Birthdays'})],components:[createButtonRow([createPanelButton(CustomIds.BirthdaySetOpen,'Set Birthday',ButtonStyle.Primary,'🎂')])]};}
 async buildManagerPanel(g){const [c,ps]=await Promise.all([this.getConfig(g),this.listBirthdays(g)]);return{embeds:[createBaseEmbed({title:'Birthday Manager',description:[`Status: **${c?.enabled?'Enabled':'Disabled'}**`,`Announcement Channel: ${c?.channel_id?`<#${c.channel_id}>`:'Not set'}`,`Birthday Role: ${c?.birthday_role_id?`<@&${c.birthday_role_id}>`:'Not set'}`,`Saved Birthdays: **${ps.length}**`].join('\n'),color:c?SlickBotColors.PRIMARY:SlickBotColors.WARNING})]};}
 async buildListPanel(g){const ps=await this.listBirthdays(g);return{embeds:[createBaseEmbed({title:'Server Birthdays',description:ps.length?ps.slice(0,50).map(p=>`• <@${p.user_id}> — **${formatBirthday(p.birth_month,p.birth_day)}**`).join('\n'):'No birthdays have been saved.',color:ps.length?SlickBotColors.INFO:SlickBotColors.WARNING})]};}
 async sendTestBirthday({guild,channel,user}){const c=await this.getConfig(guild.id);const target=channel||(c?.channel_id?await guild.channels.fetch(c.channel_id).catch(()=>null):null);if(!target?.send)return{ok:false,reason:'Configure a birthday channel or choose one.'};const text=String(c?.announcement_template||'Happy birthday {user}! 🎉').replaceAll('{user}',`<@${user.id}>`).replaceAll('{username}',user.username).replaceAll('{server}',guild.name).replaceAll('{date}','today');await target.send(text);return{ok:true,channel:target};}
 async processBirthdays(client,logger){const configs=(await query(`SELECT * FROM birthday_configs WHERE enabled=true AND channel_id IS NOT NULL`)).rows;let count=0;for(const c of configs){const now=new Date(new Date().toLocaleString('en-US',{timeZone:c.timezone||'America/New_York'}));const ps=(await query(`SELECT * FROM birthday_profiles WHERE guild_id=$1 AND active=true AND birth_month=$2 AND birth_day=$3`,[c.guild_id,now.getMonth()+1,now.getDate()])).rows;const guild=await client.guilds.fetch(c.guild_id).catch(()=>null);const channel=await client.channels.fetch(c.channel_id).catch(()=>null);for(const p of ps){const key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;const inserted=await query(`INSERT INTO birthday_announcements(guild_id,user_id,announcement_date) VALUES($1,$2,$3) ON CONFLICT(guild_id,user_id,announcement_date) DO NOTHING RETURNING id`,[c.guild_id,p.user_id,key]);if(!inserted.rowCount)continue;const member=await guild?.members.fetch(p.user_id).catch(()=>null);if(member&&c.birthday_role_id)await member.roles.add(c.birthday_role_id,'SlickBot birthday').catch(()=>{});if(channel?.send)await channel.send(String(c.announcement_template||'Happy birthday {user}! 🎉').replaceAll('{user}',`<@${p.user_id}>`).replaceAll('{username}',p.user_tag||'member').replaceAll('{server}',guild?.name||'the server').replaceAll('{date}',formatBirthday(p.birth_month,p.birth_day))).catch(()=>{});count++;await logger?.log({guildId:c.guild_id,eventKey:'birthday-active',title:'Birthday Announced',body:`User: <@${p.user_id}>`}).catch(()=>{});}}return count;}
}
module.exports={BirthdayService,birthdaySavedEmbed,birthdayNotFoundEmbed,formatBirthday,timezoneChoicesForAutocomplete,MONTH_NAMES,validDate};
