const { ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
const { query } = require('../../services/db');
const { createBaseEmbed, SlickBotColors } = require('../ui/uiService');
const ENTRY_PREFIX='slickbot:giveaway:enter:';
function parseDuration(v){const m=String(v||'').trim().match(/^(\d+)\s*([mhdw])$/i);if(!m)return null;return Number(m[1])*({m:60000,h:3600000,d:86400000,w:604800000}[m[2].toLowerCase()]);}
class GiveawayService{
 async getConfig(g){const r=await query('SELECT * FROM giveaway_configs WHERE guild_id=$1 LIMIT 1',[g]);return r.rows[0]||null;}
 async updateConfig(g,i){const r=await query(`INSERT INTO giveaway_configs(guild_id,default_channel_id,ping_role_id,host_role_id,panel_color) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guild_id) DO UPDATE SET default_channel_id=COALESCE(EXCLUDED.default_channel_id,giveaway_configs.default_channel_id),ping_role_id=COALESCE(EXCLUDED.ping_role_id,giveaway_configs.ping_role_id),host_role_id=COALESCE(EXCLUDED.host_role_id,giveaway_configs.host_role_id),panel_color=COALESCE(EXCLUDED.panel_color,giveaway_configs.panel_color),updated_at=NOW() RETURNING *`,[g,i.defaultChannelId||null,i.pingRoleId||null,i.hostRoleId||null,i.panelColor||null]);return r.rows[0];}
 async startGiveaway({interaction,client,logger,channel,prize,description,duration,winnerCount}){const ms=parseDuration(duration);if(!ms)return{ok:false,reason:'Use a duration such as `30m`, `2h`, `1d`, or `1w`.'};const cfg=await this.getConfig(interaction.guildId);let target=channel;if(!target&&cfg?.default_channel_id)target=await client.channels.fetch(cfg.default_channel_id).catch(()=>null);target=target||interaction.channel;if(!target?.send)return{ok:false,reason:'A valid giveaway channel is required.'};const next=await query('SELECT COALESCE(MAX(giveaway_number),0)+1 n FROM giveaways WHERE guild_id=$1',[interaction.guildId]);const endAt=new Date(Date.now()+ms);const r=await query(`INSERT INTO giveaways(guild_id,giveaway_number,channel_id,host_user_id,prize,description,winner_count,end_at,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'OPEN') RETURNING *`,[interaction.guildId,next.rows[0].n,target.id,interaction.user.id,prize,description||null,winnerCount||1,endAt]);const g=r.rows[0];const message=await target.send(this.buildPayload(g,cfg));await query('UPDATE giveaways SET message_id=$1 WHERE id=$2',[message.id,g.id]);g.message_id=message.id;await logger?.log({guildId:interaction.guildId,eventKey:'giveaway-created',title:'Giveaway Created',body:`Giveaway #${g.giveaway_number}: **${g.prize}**`,actorUserId:interaction.user.id}).catch(()=>{});return{ok:true,giveaway:g,channel:target};}
 buildPayload(g,cfg={}){let color=SlickBotColors.PRIMARY;const raw=String(cfg?.panel_color||'').replace('#','');if(/^[0-9a-f]{6}$/i.test(raw))color=parseInt(raw,16);return{content:cfg?.ping_role_id?`<@&${cfg.ping_role_id}>`:undefined,embeds:[createBaseEmbed({title:`🎉 ${g.prize}`,description:[g.description||'Click below to enter.',`Winners: **${g.winner_count}**`,`Ends: <t:${Math.floor(new Date(g.end_at).getTime()/1000)}:R>`,`Status: **${g.status}**`].join('\n'),color,footer:`SlickBot Giveaway #${g.giveaway_number}`})],components:g.status==='OPEN'?[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`${ENTRY_PREFIX}${g.id}`).setLabel('Enter Giveaway').setEmoji('🎉').setStyle(ButtonStyle.Primary))]:[]};}
 async enter(guildId,giveawayId,user,logger){const g=(await query(`SELECT * FROM giveaways WHERE guild_id=$1 AND id=$2 AND status='OPEN' AND end_at>NOW()`,[guildId,giveawayId])).rows[0];if(!g)return{ok:false,reason:'This giveaway is no longer open.'};await query(`INSERT INTO giveaway_entries(giveaway_id,user_id,user_tag) VALUES($1,$2,$3) ON CONFLICT(giveaway_id,user_id) DO NOTHING`,[g.id,user.id,user.tag]);await logger?.log({guildId,eventKey:'giveaway-entry',title:'Giveaway Entry',body:`<@${user.id}> entered giveaway #${g.giveaway_number}.`,actorUserId:user.id}).catch(()=>{});return{ok:true,giveaway:g};}
 async endGiveaway({client,guildId,giveawayNumber,actorUserId,logger,reroll=false}){const g=(await query('SELECT * FROM giveaways WHERE guild_id=$1 AND giveaway_number=$2 LIMIT 1',[guildId,giveawayNumber])).rows[0];if(!g)return{ok:false,reason:'Giveaway not found.'};if(!reroll&&g.status!=='OPEN')return{ok:false,reason:'This giveaway has already ended.'};const entries=(await query('SELECT user_id FROM giveaway_entries WHERE giveaway_id=$1',[g.id])).rows.sort(()=>Math.random()-.5);const winners=entries.slice(0,Number(g.winner_count)||1).map(x=>x.user_id);const status='ENDED';const updated=(await query(`UPDATE giveaways SET status=$1,winner_user_ids=$2::jsonb,ended_at=NOW(),updated_at=NOW() WHERE id=$3 RETURNING *`,[status,JSON.stringify(winners),g.id])).rows[0];const ch=await client.channels.fetch(g.channel_id).catch(()=>null);const msg=ch?.messages&&g.message_id?await ch.messages.fetch(g.message_id).catch(()=>null):null;await msg?.edit(this.buildPayload(updated,await this.getConfig(guildId))).catch(()=>{});if(ch?.send)await ch.send(winners.length?`Congratulations ${winners.map(id=>`<@${id}>`).join(', ')}! You won **${g.prize}**.`:`Giveaway **${g.prize}** ended with no eligible entries.`).catch(()=>{});await logger?.log({guildId,eventKey:reroll?'giveaway-rerolled':'giveaway-ended',title:reroll?'Giveaway Rerolled':'Giveaway Ended',body:`Giveaway #${g.giveaway_number}; winners: **${winners.length}**`,actorUserId}).catch(()=>{});return{ok:true,giveaway:updated,winners};}
 async processDueGiveaways(client,logger){const rows=(await query(`SELECT guild_id,giveaway_number FROM giveaways WHERE status='OPEN' AND end_at<=NOW()`)).rows;for(const r of rows)await this.endGiveaway({client,guildId:r.guild_id,giveawayNumber:r.giveaway_number,actorUserId:null,logger}).catch(()=>{});return rows.length;}
 async buildManagerPanel(guildId){const [cfg,active]=await Promise.all([this.getConfig(guildId),query(`SELECT * FROM giveaways WHERE guild_id=$1 AND status='OPEN' ORDER BY end_at LIMIT 10`,[guildId])]);return{embeds:[createBaseEmbed({title:'Giveaway Manager',description:[`Default Channel: ${cfg?.default_channel_id?`<#${cfg.default_channel_id}>`:'Not set'}`,`Active Giveaways: **${active.rowCount}**`,active.rowCount?active.rows.map(g=>`• #${g.giveaway_number} **${g.prize}** — <t:${Math.floor(new Date(g.end_at).getTime()/1000)}:R>`).join('\n'):'No active giveaways.'].join('\n'),color:cfg?SlickBotColors.PRIMARY:SlickBotColors.WARNING})]};}
}
module.exports={GiveawayService,ENTRY_PREFIX,parseDuration};
