const { query } = require('../../services/db');
const { createBaseEmbed, SlickBotColors } = require('../ui/uiService');
function totalXpForLevel(level){const l=Math.max(0,Number(level)||0);return 5*l*l+50*l+100;}
function levelFromXp(xp){let l=0;while(l<10000&&totalXpForLevel(l+1)<=xp)l++;return l;}
function formatMultiplier(v){return `${Number(v||1).toFixed(Number(v)%1?2:0).replace(/\.00$/,'')}×`;}
function arr(v){if(Array.isArray(v))return v;if(!v)return[];try{return JSON.parse(v)||[];}catch{return[];}}
class LevelingService{
 async getConfig(g){const r=await query('SELECT * FROM leveling_configs WHERE guild_id=$1 LIMIT 1',[g]);return r.rows[0]||null;}
 async saveConfig(g,i){const old=await this.getConfig(g)||{};const v={enabled:i.enabled??old.enabled??true,min:i.xpMin??old.xp_min??15,max:i.xpMax??old.xp_max??25,cool:i.cooldownSeconds??old.cooldown_seconds??60,len:i.minimumMessageLength??old.minimum_message_length??3,ch:i.levelUpChannelId??old.level_up_channel_id??null,msg:i.levelUpMessage??old.level_up_message??'Congratulations {user}! You reached level **{level}**.',mode:i.levelUpAnnounceMode??old.level_up_announce_mode??'ALL_LEVELS',ic:arr(old.ignored_channel_ids),ir:arr(old.ignored_role_ids)};if(v.max<v.min)v.max=v.min;const r=await query(`INSERT INTO leveling_configs(guild_id,enabled,xp_min,xp_max,cooldown_seconds,minimum_message_length,level_up_channel_id,level_up_message,level_up_announce_mode,ignored_channel_ids,ignored_role_ids) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb) ON CONFLICT(guild_id) DO UPDATE SET enabled=EXCLUDED.enabled,xp_min=EXCLUDED.xp_min,xp_max=EXCLUDED.xp_max,cooldown_seconds=EXCLUDED.cooldown_seconds,minimum_message_length=EXCLUDED.minimum_message_length,level_up_channel_id=EXCLUDED.level_up_channel_id,level_up_message=EXCLUDED.level_up_message,level_up_announce_mode=EXCLUDED.level_up_announce_mode,ignored_channel_ids=EXCLUDED.ignored_channel_ids,ignored_role_ids=EXCLUDED.ignored_role_ids,updated_at=NOW() RETURNING *`,[g,v.enabled,v.min,v.max,v.cool,v.len,v.ch,v.msg,v.mode,JSON.stringify(v.ic),JSON.stringify(v.ir)]);return r.rows[0];}
 async getProfile(g,u){return (await query('SELECT * FROM leveling_profiles WHERE guild_id=$1 AND user_id=$2 LIMIT 1',[g,u])).rows[0]||null;}
 async processMessage(message,logger){const c=await this.getConfig(message.guild.id);if(!c||c.enabled===false||message.author.bot)return{awarded:false};if(String(message.content||'').trim().length<Number(c.minimum_message_length||3)||arr(c.ignored_channel_ids).includes(message.channelId))return{awarded:false};const roles=[...message.member.roles.cache.keys()];if(arr(c.ignored_role_ids).some(id=>roles.includes(id)))return{awarded:false};const p=await this.getProfile(message.guild.id,message.author.id);if(p?.last_xp_at&&Date.now()-new Date(p.last_xp_at).getTime()<Number(c.cooldown_seconds)*1000)return{awarded:false};const mult=await this.getApplicableMultiplier(message.guild.id,roles);const gain=Math.max(1,Math.round((Math.floor(Math.random()*(Number(c.xp_max)-Number(c.xp_min)+1))+Number(c.xp_min))*mult.multiplier));const xp=Number(p?.xp||0)+gain, old=Number(p?.level||0), level=levelFromXp(xp);const saved=(await query(`INSERT INTO leveling_profiles(guild_id,user_id,user_tag,xp,level,message_count,last_xp_at) VALUES($1,$2,$3,$4,$5,1,NOW()) ON CONFLICT(guild_id,user_id) DO UPDATE SET user_tag=EXCLUDED.user_tag,xp=EXCLUDED.xp,level=EXCLUDED.level,message_count=leveling_profiles.message_count+1,last_xp_at=NOW(),updated_at=NOW() RETURNING *`,[message.guild.id,message.author.id,message.author.tag,xp,level])).rows[0];if(level>old)await this.handleLevelUp(message,saved,old,c,logger);return{awarded:true,gained:gain,profile:saved};}
 async handleLevelUp(message,p,old,c,logger){const rewards=(await query(`SELECT * FROM leveling_role_rewards WHERE guild_id=$1 AND active=true AND level>$2 AND level<=$3 ORDER BY level`,[message.guild.id,old,p.level])).rows;for(const r of rewards)await message.member.roles.add(r.role_id,`SlickBot level ${p.level}`).catch(()=>{});if(c.level_up_channel_id&&(c.level_up_announce_mode!=='ROLE_REWARDS_ONLY'||rewards.length)){const ch=await message.guild.channels.fetch(c.level_up_channel_id).catch(()=>null);const txt=String(c.level_up_message).replaceAll('{user}',`<@${message.author.id}>`).replaceAll('{username}',message.author.username).replaceAll('{level}',String(p.level)).replaceAll('{server}',message.guild.name).replaceAll('{roles}',rewards.map(r=>`<@&${r.role_id}>`).join(', ')||'No role reward');await ch?.send(txt).catch(()=>{});}await logger?.log({guildId:message.guild.id,eventKey:'leveling-level-up',title:'Member Leveled Up',body:`User: <@${message.author.id}>\nLevel: **${p.level}**`,actorUserId:message.author.id}).catch(()=>{});}
 async addRoleReward(g,l,r){return (await query(`INSERT INTO leveling_role_rewards(guild_id,level,role_id,active) VALUES($1,$2,$3,true) ON CONFLICT(guild_id,level,role_id) DO UPDATE SET active=true,updated_at=NOW() RETURNING *`,[g,l,r])).rows[0];}
 async removeRoleReward(g,l,r=null){const q=r?`UPDATE leveling_role_rewards SET active=false,updated_at=NOW() WHERE guild_id=$1 AND level=$2 AND role_id=$3 AND active=true RETURNING *`:`UPDATE leveling_role_rewards SET active=false,updated_at=NOW() WHERE guild_id=$1 AND level=$2 AND active=true RETURNING *`;return (await query(q,r?[g,l,r]:[g,l])).rows;}
 async listRoleRewards(g){return (await query(`SELECT * FROM leveling_role_rewards WHERE guild_id=$1 AND active=true ORDER BY level,created_at`,[g])).rows;}
 async addMultiplierRole(g,r,m){return (await query(`INSERT INTO leveling_multiplier_roles(guild_id,role_id,multiplier,active) VALUES($1,$2,$3,true) ON CONFLICT(guild_id,role_id) DO UPDATE SET multiplier=EXCLUDED.multiplier,active=true,updated_at=NOW() RETURNING *`,[g,r,Math.max(.1,Number(m)||1)])).rows[0];}
 async removeMultiplierRole(g,r){return (await query(`UPDATE leveling_multiplier_roles SET active=false,updated_at=NOW() WHERE guild_id=$1 AND role_id=$2 RETURNING *`,[g,r])).rows[0]||null;}
 async listMultiplierRoles(g){return (await query(`SELECT * FROM leveling_multiplier_roles WHERE guild_id=$1 AND active=true ORDER BY multiplier ASC,created_at`,[g])).rows;}
 async getApplicableMultiplier(g,roles){if(!roles.length)return{multiplier:1,roleId:null};const r=await query(`SELECT role_id,multiplier FROM leveling_multiplier_roles WHERE guild_id=$1 AND active=true AND role_id=ANY($2) ORDER BY multiplier DESC LIMIT 1`,[g,roles]);return r.rows[0]?{multiplier:Number(r.rows[0].multiplier),roleId:r.rows[0].role_id}:{multiplier:1,roleId:null};}
 async setXp(g,u,xp){const safe=Math.max(0,Math.floor(xp));return (await query(`INSERT INTO leveling_profiles(guild_id,user_id,user_tag,xp,level,message_count) VALUES($1,$2,$3,$4,$5,0) ON CONFLICT(guild_id,user_id) DO UPDATE SET user_tag=EXCLUDED.user_tag,xp=EXCLUDED.xp,level=EXCLUDED.level,updated_at=NOW() RETURNING *`,[g,u.id,u.tag,safe,levelFromXp(safe)])).rows[0];}
 async resetProfile(g,u){return (await query('DELETE FROM leveling_profiles WHERE guild_id=$1 AND user_id=$2 RETURNING *',[g,u])).rows[0]||null;}
 async getRank(g,u){return (await query(`SELECT p.*, (SELECT COUNT(*)+1 FROM leveling_profiles x WHERE x.guild_id=p.guild_id AND x.xp>p.xp)::int rank FROM leveling_profiles p WHERE p.guild_id=$1 AND p.user_id=$2`,[g,u])).rows[0]||null;}
 async leaderboard(g,n=10){return (await query(`SELECT * FROM leveling_profiles WHERE guild_id=$1 ORDER BY xp DESC LIMIT $2`,[g,n])).rows;}
 buildRankEmbed(user,d){return createBaseEmbed({title:`Rank • ${user.tag}`,description:d?`Level: **${d.level}**\nXP: **${Number(d.xp).toLocaleString()}**\nRank: **#${d.rank}**\nMessages: **${d.message_count}**`:'This user has not earned XP yet.',color:d?SlickBotColors.PRIMARY:SlickBotColors.WARNING});}
 buildLeaderboardEmbed(rows){return createBaseEmbed({title:'XP Leaderboard',description:rows.length?rows.map((p,i)=>`${i+1}. <@${p.user_id}> — **${Number(p.xp).toLocaleString()} XP** · Level ${p.level}`).join('\n'):'No XP profiles yet.',color:rows.length?SlickBotColors.INFO:SlickBotColors.WARNING});}
 async addIgnoredChannel(g,id){const c=await this.getConfig(g)||await this.saveConfig(g,{});const a=[...new Set([...arr(c.ignored_channel_ids),id])];await query('UPDATE leveling_configs SET ignored_channel_ids=$1::jsonb,updated_at=NOW() WHERE guild_id=$2',[JSON.stringify(a),g]);}
 async removeIgnoredChannel(g,id){const c=await this.getConfig(g);await query('UPDATE leveling_configs SET ignored_channel_ids=$1::jsonb,updated_at=NOW() WHERE guild_id=$2',[JSON.stringify(arr(c?.ignored_channel_ids).filter(x=>x!==id)),g]);}
 async addIgnoredRole(g,id){const c=await this.getConfig(g)||await this.saveConfig(g,{});await query('UPDATE leveling_configs SET ignored_role_ids=$1::jsonb,updated_at=NOW() WHERE guild_id=$2',[JSON.stringify([...new Set([...arr(c.ignored_role_ids),id])]),g]);}
 async removeIgnoredRole(g,id){const c=await this.getConfig(g);await query('UPDATE leveling_configs SET ignored_role_ids=$1::jsonb,updated_at=NOW() WHERE guild_id=$2',[JSON.stringify(arr(c?.ignored_role_ids).filter(x=>x!==id)),g]);}
 buildXpAnalysis(c,max=100,m=1){const rows=[];const avg=(Number(c?.xp_min||15)+Number(c?.xp_max||25))/2*Number(m);for(let l=1;l<=max;l++){const total=totalXpForLevel(l);rows.push({level:l,totalXp:total,incrementalXp:total-(l>1?totalXpForLevel(l-1):0),estimatedMessagesTotal:Math.ceil(total/avg)});}return{rows,maxLevel:max,multiplier:m,averageBaseXp:avg/Number(m),averageAward:avg};}
 buildXpAnalysisCsv(a){return 'Level,XP From Previous Level,Total XP Required,Estimated Messages Total\n'+a.rows.map(r=>`${r.level},${r.incrementalXp},${r.totalXp},${r.estimatedMessagesTotal}`).join('\n')+'\n';}
 buildXpAnalysisEmbed(a){return createBaseEmbed({title:'SlickBot XP Curve Analysis',description:`Levels: **1–${a.maxLevel}**\nAverage award: **${a.averageAward.toFixed(1)} XP**\nMultiplier: **${formatMultiplier(a.multiplier)}**\nA CSV with every level is attached.`,color:SlickBotColors.INFO});}
 async buildInfoEmbed(guild){const [c,rewards,mults]=await Promise.all([this.getConfig(guild.id),this.listRoleRewards(guild.id),this.listMultiplierRoles(guild.id)]);if(!c)return createBaseEmbed({title:'Server Levels',description:'Leveling has not been configured.',color:SlickBotColors.WARNING});const s=['## Earn XP',`Chat normally to earn **${c.xp_min}–${c.xp_max} XP** every **${c.cooldown_seconds} seconds**.`,`Use \`/level rank\` and \`/level leaderboard\`.`];if(mults.length)s.push('','## XP Multipliers',...mults.map(x=>`• <@&${x.role_id}> — **${formatMultiplier(x.multiplier)}**`),'_Only the highest multiplier applies._');if(rewards.length)s.push('','## Level Rewards',...rewards.slice(0,20).map(x=>`• **Level ${x.level}** → <@&${x.role_id}>`));return createBaseEmbed({title:'Server Levels',description:s.join('\n'),color:SlickBotColors.PRIMARY,footer:`${guild.name} · SlickBot Leveling`});}
 async buildManagerPanel(g){const [c,p,r,m]=await Promise.all([this.getConfig(g),query('SELECT COUNT(*)::int count FROM leveling_profiles WHERE guild_id=$1',[g]),this.listRoleRewards(g),this.listMultiplierRoles(g)]);return{embeds:[createBaseEmbed({title:'SlickBot Leveling Center',description:c?[`Status: **${c.enabled?'Enabled':'Disabled'}**`,`XP Range: **${c.xp_min}–${c.xp_max}**`,`Cooldown: **${c.cooldown_seconds}s**`,`Profiles: **${p.rows[0].count}**`,`Role Rewards: **${r.length}**`,`Multiplier Roles: **${m.length}**`].join('\n'):'Run `/level setup` to configure leveling.',color:c?SlickBotColors.PRIMARY:SlickBotColors.WARNING})]};}
}
module.exports={LevelingService,formatMultiplier,totalXpForLevel,levelFromXp};
