const { ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder } = require('discord.js');
const { query } = require('../../services/db');
const { createBaseEmbed, SlickBotColors } = require('../ui/uiService');
function parseColor(v){const x=String(v||'').replace('#','');return /^[0-9a-f]{6}$/i.test(x)?parseInt(x,16):SlickBotColors.PRIMARY;}
function styleFromHex(v){if(!v)return ButtonStyle.Primary;const n=parseColor(v),r=(n>>16)&255,g=(n>>8)&255,b=n&255;if(r>g*1.25&&r>b*1.25)return ButtonStyle.Danger;if(g>r*1.15&&g>b*1.15)return ButtonStyle.Success;return ButtonStyle.Primary;}
async function getPanelByName(g,n){return(await query(`SELECT * FROM role_panels WHERE guild_id=$1 AND LOWER(name)=LOWER($2) AND active=true LIMIT 1`,[g,n])).rows[0]||null;}
async function getPanelById(g,id){return(await query(`SELECT * FROM role_panels WHERE guild_id=$1 AND id=$2 AND active=true LIMIT 1`,[g,id])).rows[0]||null;}
async function createPanel(i){return(await query(`INSERT INTO role_panels(guild_id,name,title,description,selection_mode,panel_color,panel_display_mode,active) VALUES($1,$2,$3,$4,$5,$6,$7,true) ON CONFLICT(guild_id,name) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,selection_mode=EXCLUDED.selection_mode,panel_color=EXCLUDED.panel_color,panel_display_mode=EXCLUDED.panel_display_mode,active=true,updated_at=NOW() RETURNING *`,[i.guildId,i.name,i.title||i.name,i.description||'Select your roles below.',i.mode||'MULTI',i.color||'#7869ff',i.displayMode||'BUTTONS'])).rows[0];}
async function deletePanel(g,n){return(await query(`UPDATE role_panels SET active=false,updated_at=NOW() WHERE guild_id=$1 AND LOWER(name)=LOWER($2) AND active=true RETURNING *`,[g,n])).rows[0]||null;}
async function setPanelDisplayMode({guildId,panelName,displayMode}){return(await query(`UPDATE role_panels SET panel_display_mode=$1,updated_at=NOW() WHERE guild_id=$2 AND LOWER(name)=LOWER($3) AND active=true RETURNING *`,[displayMode,guildId,panelName])).rows[0]||null;}
async function listOptions(id){return(await query(`SELECT * FROM role_panel_options WHERE panel_id=$1 AND active=true ORDER BY display_order,created_at`,[id])).rows;}
async function addOption(i){const p=await getPanelByName(i.guildId,i.panelName);if(!p)return null;const order=(await listOptions(p.id)).length+1;const o=(await query(`INSERT INTO role_panel_options(panel_id,role_id,role_ids,label,emoji,description,button_color,display_order,active,option_key) VALUES($1,$2,$3::jsonb,$4,$5,$6,$7,$8,true,$9) ON CONFLICT(panel_id,option_key) DO UPDATE SET label=EXCLUDED.label,emoji=EXCLUDED.emoji,description=EXCLUDED.description,button_color=EXCLUDED.button_color,active=true,updated_at=NOW() RETURNING *`,[p.id,i.roleId,JSON.stringify([i.roleId]),i.label||'',i.emoji||null,i.description||null,i.buttonColor||'#5865f2',order,`role:${i.roleId}`])).rows[0];return{panel:p,option:o};}
async function addBundleOption(i){const p=await getPanelByName(i.guildId,i.panelName);if(!p)return null;const ids=[...new Set(i.roleIds)];const key=`bundle:${ids.join(',')}`;const o=(await query(`INSERT INTO role_panel_options(panel_id,role_id,role_ids,label,emoji,description,button_color,display_order,active,option_key) VALUES($1,$2,$3::jsonb,$4,$5,$6,$7,$8,true,$9) ON CONFLICT(panel_id,option_key) DO UPDATE SET role_ids=EXCLUDED.role_ids,label=EXCLUDED.label,emoji=EXCLUDED.emoji,description=EXCLUDED.description,button_color=EXCLUDED.button_color,active=true,updated_at=NOW() RETURNING *`,[p.id,ids[0],JSON.stringify(ids),i.label||'',i.emoji||null,i.description||null,i.buttonColor||'#5865f2',(await listOptions(p.id)).length+1,key])).rows[0];return{panel:p,option:o};}
function parseBulkEntries(text){return String(text||'').split(/\r?\n/).filter(Boolean).map(line=>{const [roles,label='',emoji='',buttonColor='']=line.split('|');const roleIds=roles.match(/\d{15,25}/g)||[];return{valid:roleIds.length>0,roleIds,label,emoji:emoji||null,buttonColor:buttonColor||null};});}
async function bulkAddOptions({guildId,panelName,entries}){const out=[];for(const e of entries){const r=e.roleIds.length>1?await addBundleOption({guildId,panelName,...e}):await addOption({guildId,panelName,roleId:e.roleIds[0],...e});if(r)out.push(r);}return out;}
async function removeOption(g,panelName,roleId){const p=await getPanelByName(g,panelName);if(!p)return null;await query(`UPDATE role_panel_options SET active=false,updated_at=NOW() WHERE panel_id=$1 AND (role_id=$2 OR role_ids ? $2)`,[p.id,roleId]);return p;}
async function removeAllOptions(g,panelName){const p=await getPanelByName(g,panelName);if(!p)return null;const r=await query(`UPDATE role_panel_options SET active=false,updated_at=NOW() WHERE panel_id=$1 AND active=true RETURNING *`,[p.id]);return{panel:p,count:r.rowCount};}
function roleIds(o){if(Array.isArray(o.role_ids))return o.role_ids;try{return JSON.parse(o.role_ids||'[]');}catch{return o.role_id?[o.role_id]:[];}}
async function buildRolePanelMessage(panel){const opts=await listOptions(panel.id);const embed=createBaseEmbed({title:panel.title||panel.name,description:panel.description||'Select your roles below.',color:parseColor(panel.panel_color),footer:'SlickBot Roles'});if(panel.panel_display_mode==='DROPDOWN'){const select=new StringSelectMenuBuilder().setCustomId(`slickbot:rolepanel-select:${panel.id}`).setPlaceholder('Choose a role...').setMinValues(1).setMaxValues(panel.selection_mode==='SINGLE'?1:Math.min(opts.length,25)).addOptions(opts.slice(0,25).map(o=>({label:(o.label||`Role ${o.role_id}`).slice(0,100),value:o.id,description:o.description?.slice(0,100),emoji:o.emoji||undefined})));return{embeds:[embed],components:[new ActionRowBuilder().addComponents(select)]};}const rows=[];for(let i=0;i<Math.min(opts.length,25);i+=5){rows.push(new ActionRowBuilder().addComponents(opts.slice(i,i+5).map(o=>{const b=new ButtonBuilder().setCustomId(`slickbot:rolepanel:${panel.id}:${o.id}`).setLabel((o.label||'Role').slice(0,80)).setStyle(styleFromHex(o.button_color));if(o.emoji)b.setEmoji(o.emoji);return b;})));}return{embeds:[embed],components:rows};}
async function toggleRole({interaction,panelId,optionId,logger}){const p=await getPanelById(interaction.guildId,panelId);if(!p)return{ok:false,reason:'Role panel not found.'};const o=(await query(`SELECT * FROM role_panel_options WHERE panel_id=$1 AND id=$2 AND active=true`,[p.id,optionId])).rows[0];if(!o)return{ok:false,reason:'Role option not found.'};const ids=roleIds(o);const has=ids.every(id=>interaction.member.roles.cache.has(id));if(p.selection_mode==='SINGLE'&&!has){const all=await listOptions(p.id);const remove=[...new Set(all.flatMap(roleIds).filter(id=>!ids.includes(id)&&interaction.member.roles.cache.has(id)))];if(remove.length)await interaction.member.roles.remove(remove,'SlickBot single-select role panel').catch(()=>{});}if(has)await interaction.member.roles.remove(ids,'SlickBot self role removal');else await interaction.member.roles.add(ids,'SlickBot self role assignment');await logger?.log({guildId:interaction.guildId,eventKey:'reaction-role-toggle',title:'Role Panel Used',body:`User: <@${interaction.user.id}>\nPanel: **${p.name}**`,actorUserId:interaction.user.id}).catch(()=>{});return{ok:true,added:!has,roleIds:ids};}
async function buildRoleManagerPanel(g){const ps=(await query(`SELECT * FROM role_panels WHERE guild_id=$1 AND active=true ORDER BY name`,[g])).rows;return{embeds:[createBaseEmbed({title:'Role Panel Manager',description:ps.length?ps.map(p=>`• **${p.name}** — ${p.panel_display_mode||'BUTTONS'} · ${p.selection_mode}`).join('\n'):'No role panels configured. Use `/roles create-panel`.',color:ps.length?SlickBotColors.PRIMARY:SlickBotColors.WARNING})]};}
async function updatePublishedRolePanelMessages(){return{updated:0,total:0};}
async function handleReactionRole(){return false;}async function syncAllPublishedReactionPanels(){return{messages:0,added:0};}
function formatRoleMentions(ids){return ids.map(id=>`<@&${id}>`).join(', ');}
module.exports={getPanelByName,getPanelById,createPanel,deletePanel,setPanelDisplayMode,addOption,addBundleOption,bulkAddOptions,parseBulkEntries,removeOption,removeAllOptions,buildRolePanelMessage,toggleRole,buildRoleManagerPanel,updatePublishedRolePanelMessages,handleReactionRole,syncAllPublishedReactionPanels,formatRoleMentions};
