const { query } = require('../../services/db');
const { createBaseEmbed, SlickBotColors } = require('../ui/uiService');
class ServerStatsService {
  async getConfig(guildId){const r=await query('SELECT * FROM server_stats_configs WHERE guild_id=$1 LIMIT 1',[guildId]);return r.rows[0]||null;}
  async setup(guildId,input){const old=await this.getConfig(guildId)||{};const v={enabled:input.enabled??old.enabled??true,member:input.memberChannelId??old.member_channel_id??null,human:input.humanChannelId??old.human_channel_id??null,bot:input.botChannelId??old.bot_channel_id??null,voice:input.voiceChannelId??old.voice_channel_id??null,mt:input.memberTemplate??old.member_template??'Members: {members}',ht:input.humanTemplate??old.human_template??'Humans: {humans}',bt:input.botTemplate??old.bot_template??'Bots: {bots}',vt:input.voiceTemplate??old.voice_template??'In Voice: {voice}'};const r=await query(`INSERT INTO server_stats_configs(guild_id,enabled,member_channel_id,human_channel_id,bot_channel_id,voice_channel_id,member_template,human_template,bot_template,voice_template) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(guild_id) DO UPDATE SET enabled=EXCLUDED.enabled,member_channel_id=EXCLUDED.member_channel_id,human_channel_id=EXCLUDED.human_channel_id,bot_channel_id=EXCLUDED.bot_channel_id,voice_channel_id=EXCLUDED.voice_channel_id,member_template=EXCLUDED.member_template,human_template=EXCLUDED.human_template,bot_template=EXCLUDED.bot_template,voice_template=EXCLUDED.voice_template,updated_at=NOW() RETURNING *`,[guildId,v.enabled,v.member,v.human,v.bot,v.voice,v.mt,v.ht,v.bt,v.vt]);return r.rows[0];}
  async updateStats(guild,logger,reason='update'){const c=await this.getConfig(guild.id);if(!c||c.enabled===false)return{ok:false,reason:'Server stats are not enabled.',updated:0};await guild.members.fetch().catch(()=>{});const members=guild.memberCount||guild.members.cache.size;const bots=guild.members.cache.filter(m=>m.user.bot).size;const humans=Math.max(0,members-bots);const voice=guild.channels.cache.filter(ch=>ch.isVoiceBased?.()).reduce((n,ch)=>n+ch.members.size,0);const items=[[c.member_channel_id,c.member_template,{members}],[c.human_channel_id,c.human_template,{humans}],[c.bot_channel_id,c.bot_template,{bots}],[c.voice_channel_id,c.voice_template,{voice}]];let updated=0;for(const[id,tpl,data]of items){if(!id)continue;const ch=await guild.channels.fetch(id).catch(()=>null);if(!ch)continue;let name=String(tpl||'').replaceAll('{members}',members).replaceAll('{humans}',humans).replaceAll('{bots}',bots).replaceAll('{voice}',voice).slice(0,100);if(name&&ch.name!==name&&await ch.setName(name,`SlickBot stats: ${reason}`).then(()=>true).catch(()=>false))updated++;}await logger?.log({guildId:guild.id,eventKey:'server-stats-update',title:'Server Stats Updated',body:`Updated **${updated}** channel(s).`,metadata:{reason,updated}}).catch(()=>{});return{ok:true,updated};}
  async buildManagerPanel(guild){const c=await this.getConfig(guild.id);return{embeds:[createBaseEmbed({title:'Server Stats Manager',description:c?[`Status: **${c.enabled?'Enabled':'Disabled'}**`,`Member Counter: ${c.member_channel_id?`<#${c.member_channel_id}>`:'Not set'}`,`Human Counter: ${c.human_channel_id?`<#${c.human_channel_id}>`:'Not set'}`,`Bot Counter: ${c.bot_channel_id?`<#${c.bot_channel_id}>`:'Not set'}`,`Voice Counter: ${c.voice_channel_id?`<#${c.voice_channel_id}>`:'Not set'}`].join('\n'):'Run `/stats setup` to configure server counters.',color:c?SlickBotColors.PRIMARY:SlickBotColors.WARNING})]};}
}
module.exports={ServerStatsService};
