const CustomIds = Object.freeze({
  SetupRefresh: 'slickbot:setup:refresh',
  SetupModules: 'slickbot:setup:modules',
  SetupLogging: 'slickbot:setup:logging',
  LoggingRefresh: 'slickbot:logging:refresh',
  LoggingTest: 'slickbot:logging:test',
  LoggingReset: 'slickbot:logging:reset',
  LoggingResetConfirm: 'slickbot:logging:reset:confirm',
  LoggingResetCancel: 'slickbot:logging:reset:cancel',
  SetupStatus: 'slickbot:setup:status',
  SetupTeams: 'slickbot:setup:teams',
  SetupPermissions: 'slickbot:setup:permissions',
  SetupCategoryCore: 'slickbot:setup:cat:core',
  SetupCategorySupport: 'slickbot:setup:cat:support',
  SetupCategoryCommunity: 'slickbot:setup:cat:community',
  SetupCategoryAutomation: 'slickbot:setup:cat:automation',
  SetupCategorySelect: 'slickbot:setup:cat:select',
  SetupModuleSelect: 'slickbot:setup:module:select',
  CategoryToggleSelectPrefix: 'slickbot:setup:cattoggle:',
  ModuleTogglePrefix: 'slickbot:mod:toggle:',
  OnboardingStart: 'slickbot:onboarding:start',
  OnboardingServerStart: 'slickbot:onboarding:server-start',
  OnboardingModulePrefix: 'slickbot:onboarding:mod:',
  OnboardingNextPrefix: 'slickbot:onboarding:next:',
  OnboardingAutoCreatePrefix: 'slickbot:onboarding:auto:',
  OnboardingSkipPrefix: 'slickbot:onboarding:skip:',
  OnboardingKeepCurrentPrefix: 'slickbot:onboarding:current:',
  OnboardingKeepDefaultPrefix: 'slickbot:onboarding:default:',
  OnboardingDisablePrefix: 'slickbot:onboarding:disable:',
  OnboardingCancelPrefix: 'slickbot:onboarding:cancel:',
  OnboardingChannelSelectPrefix: 'slickbot:onboarding:chsel:',
  OnboardingRoleSelectPrefix: 'slickbot:onboarding:rolesel:',
  OnboardingTogglePrefix: 'slickbot:onboarding:toggle:',
  ResetConfirm: 'slickbot:reset:confirm',
  ResetCancel: 'slickbot:reset:cancel',
  PermissionsRefresh: 'slickbot:permissions:refresh',
  PermissionsModuleSelect: 'slickbot:permissions:module-select',
  PermissionsCommandSelect: 'slickbot:permissions:command-select',
  PermissionsTeamSelect: 'slickbot:permissions:team-select',
  PermissionsSetAdminRole: 'slickbot:permissions:set-admin-role',
  PermissionsSetModRole: 'slickbot:permissions:set-mod-role',
  PermissionsApplyDefaults: 'slickbot:permissions:apply-defaults',


  HelpRefresh: 'slickbot:help:refresh',
  HelpEnabled: 'slickbot:help:enabled',
  HelpDisabled: 'slickbot:help:disabled',
  HelpEnabledSelect: 'slickbot:help:enabled-select',
  HelpDisabledSelect: 'slickbot:help:disabled-select',
  HelpCategorySelect: 'slickbot:help:cat-select',
  HelpModuleSelect: 'slickbot:help:mod-select',
  HelpModePrefix: 'slickbot:help:mode:',
  HelpPagePrefix: 'slickbot:help:page:',
  HelpSearchBtn: 'slickbot:help:search-btn',
  HelpSearchModal: 'slickbot:help:search-modal',
  HelpSearchModalSubmit: 'slickbot:modal:help-search',

  ApplicationCancelPrefix: 'slickbot:application:cancel:',
  ApplicationSubmitPrefix: 'slickbot:application:submit:',
  SetupModeration: 'slickbot:setup:moderation',
  SetupSupport: 'slickbot:setup:support',
  SetupCommunity: 'slickbot:setup:community',
  WelcomeRefresh: 'slickbot:welcome:refresh',
  WelcomeToggle: 'slickbot:welcome:toggle',
  WelcomeToggleDm: 'slickbot:welcome:toggle-dm',
  WelcomeEditModal: 'slickbot:welcome:edit-modal',
  WelcomeEditModalSubmit: 'slickbot:modal:welcome-edit',
  WelcomeTest: 'slickbot:welcome:test',

  RolePanelsRefresh: 'slickbot:rolepanels:refresh',

  GiveawaysRefresh: 'slickbot:giveaways:refresh',
  GiveawaysQuickStart: 'slickbot:giveaways:quick-start',
  GiveawaysQuickStartModalSubmit: 'slickbot:modal:giveaways-start',
  GiveawaysConfigModal: 'slickbot:giveaways:config-modal',
  GiveawaysConfigModalSubmit: 'slickbot:modal:giveaways-config',

  BirthdaysRefresh: 'slickbot:birthdays:refresh',
  BirthdaysToggle: 'slickbot:birthdays:toggle',
  BirthdaysEditModal: 'slickbot:birthdays:edit-modal',
  BirthdaysEditModalSubmit: 'slickbot:modal:birthdays-edit',
  BirthdaysTest: 'slickbot:birthdays:test',
  BirthdaysPostPanel: 'slickbot:birthdays:post-panel',

  ScheduledMessagesRefresh: 'slickbot:scheduled-messages:refresh',
  ScheduledMessagesToggle: 'slickbot:scheduled-messages:toggle',
  ScheduledMessagesCreateModal: 'slickbot:scheduled-messages:create-modal',
  ScheduledMessagesCreateModalSubmit: 'slickbot:modal:scheduled-messages-create',

  ServerStatsRefresh: 'slickbot:server-stats:refresh',
  ServerStatsToggle: 'slickbot:server-stats:toggle',
  ServerStatsConfigModal: 'slickbot:server-stats:config-modal',
  ServerStatsConfigModalSubmit: 'slickbot:modal:server-stats-config',
  ServerStatsRefreshNow: 'slickbot:server-stats:refresh-now',

  LevelingRefresh: 'slickbot:leveling:refresh',
  LevelingToggle: 'slickbot:leveling:toggle',
  LevelingConfigModal: 'slickbot:leveling:config-modal',
  LevelingConfigModalSubmit: 'slickbot:modal:leveling-config',
  LevelingToggleMode: 'slickbot:leveling:toggle-mode',

  CustomCommandsRefresh: 'slickbot:custom-commands:refresh',
  CustomCommandsToggle: 'slickbot:custom-commands:toggle',
  CustomCommandsPrefixModal: 'slickbot:custom-commands:prefix-modal',
  CustomCommandsPrefixModalSubmit: 'slickbot:modal:custom-commands-prefix',
  CustomCommandsCreateModal: 'slickbot:custom-commands:create-modal',
  CustomCommandsCreateModalSubmit: 'slickbot:modal:custom-commands-create',

  JoinCreateRefresh: 'slickbot:join-create:refresh',

  GamesRefresh: 'slickbot:games:refresh',
  GamesCounting: 'slickbot:games:counting',
  GamesCountingToggle: 'slickbot:games:counting-toggle',
  GamesTicTacToe: 'slickbot:games:tic-tac-toe',
  GamesTttToggle: 'slickbot:games:ttt-toggle',
  GamesConnectFour: 'slickbot:games:connect-four',
  GamesC4Toggle: 'slickbot:games:c4-toggle',

  FaqRefresh: 'slickbot:faq:refresh',
  FaqRefreshIndex: 'slickbot:faq:refresh-index',

  SuggestionsRefresh: 'slickbot:suggestions:refresh',

  ReferralsRefresh: 'slickbot:referrals:refresh',
  ReferralsToggle: 'slickbot:referrals:toggle',
  ReferralsConfigModal: 'slickbot:referrals:config-modal',
  ReferralsConfigModalSubmit: 'slickbot:modal:referrals-config',

  TempRolesRefresh: 'slickbot:temp-roles:refresh',
  TempRolesCleanup: 'slickbot:temp-roles:cleanup',

  AchievementsRefresh: 'slickbot:achievements:refresh',
  AchievementsToggleDm: 'slickbot:achievements:toggle-dm',

  BotUpdatesRefresh: 'slickbot:bot-updates:refresh',
  BotUpdatesToggle: 'slickbot:bot-updates:toggle',
  BotUpdatesTogglePings: 'slickbot:bot-updates:toggle-pings',
  BotUpdatesPreview: 'slickbot:bot-updates:preview',
  BotUpdatesSendNow: 'slickbot:bot-updates:send-now',
  AchievementsHistoryPrefix: 'slickbot:achievements:history:',
  AchievementsResetConfirmPrefix: 'slickbot:achievements-reset:confirm:',
  AchievementsResetCancelPrefix: 'slickbot:achievements-reset:cancel:',
  FeedsRefresh: 'slickbot:feeds:refresh',
  FeedsCheckNow: 'slickbot:feeds:check-now',
  FeedsResetConfirmPrefix: 'slickbot:feeds-reset:confirm:',
  FeedsResetCancelPrefix: 'slickbot:feeds-reset:cancel:',
  SuggestionSubmitOpen: 'slickbot:suggestions:submit-open',
  SuggestionSubmitModalPrefix: 'slickbot:modal:suggestions-submit:',
  SuggestionVoteTotalPrefix: 'slickbot:suggestions:vote-total:',
  SuggestionVoteUpPrefix: 'slickbot:suggestions:vote-up:',
  SuggestionVoteDownPrefix: 'slickbot:suggestions:vote-down:',
  SuggestionReviewStatusPrefix: 'slickbot:suggestions:review-status:',
  SuggestionReviewAddDetailsPrefix: 'slickbot:suggestions:review-details:',
  SuggestionReviewRevealPrefix: 'slickbot:suggestions:review-reveal:',
  SuggestionReviewDetailsModalPrefix: 'slickbot:modal:suggestions-review-details:',
  SuggestionReviewIndexFilterPrefix: 'slickbot:suggestions:index-filter:',
  SuggestionResetConfirmPrefix: 'slickbot:suggestions-reset:confirm:',
  SuggestionResetCancelPrefix: 'slickbot:suggestions-reset:cancel:',
  GamePanelTicTacToe: 'slickbot:games:panel:tic-tac-toe',
  GamePanelConnectFour: 'slickbot:games:panel:connect-four',
  GamePanelOpponentSelectPrefix: 'slickbot:games:panel-opponent:',
  GameChallengeAcceptPrefix: 'slickbot:games:accept:',
  GameChallengeDeclinePrefix: 'slickbot:games:decline:',
  GameTicTacToeMovePrefix: 'slickbot:games:ttt:',
  GameConnectFourMovePrefix: 'slickbot:games:c4:',

  ModulesSelect: 'slickbot:modules:select',
  ModulesDetailSelect: 'slickbot:modules:detail-select',
  ModulesRefresh: 'slickbot:modules:refresh',

  LoggingRefresh: 'slickbot:logging:refresh',
  LoggingTest: 'slickbot:logging:test',

  StatusRefresh: 'slickbot:status:refresh',
  StatusActivityPlaying: 'slickbot:status:activity-playing',
  StatusActivityWatching: 'slickbot:status:activity-watching',
  StatusActivityListening: 'slickbot:status:activity-listening',
  StatusActivityCompeting: 'slickbot:status:activity-competing',
  StatusActivityStreaming: 'slickbot:status:activity-streaming',
  StatusActivityNone: 'slickbot:status:activity-none',
  StatusActivityText: 'slickbot:status:activity-text',
  StatusActivityTextModal: 'slickbot:modal:status-activity-text',
  StatusQuickOnline: 'slickbot:status:quick-online',
  StatusQuickIdle: 'slickbot:status:quick-idle',
  StatusQuickDnd: 'slickbot:status:quick-dnd',
  StatusClear: 'slickbot:status:clear',

  ModerationRefresh: 'slickbot:moderation:refresh',
  ModerationSetLogChannel: 'slickbot:moderation:set-log-channel',
  LockdownRefresh: 'slickbot:lockdown:refresh',
  LockdownResetConfirmPrefix: 'slickbot:lockdown-reset:confirm:',
  LockdownResetCancelPrefix: 'slickbot:lockdown-reset:cancel:',
  CasesRefresh: 'slickbot:cases:refresh',

  SupportRefresh: 'slickbot:support:refresh',
  SupportResetConfirmPrefix: 'slickbot:support-reset:confirm:',
  SupportResetCancelPrefix: 'slickbot:support-reset:cancel:',
  TicketsRefresh: 'slickbot:tickets:refresh',
  TicketOpen: 'slickbot:ticket:open',
  TicketOpenTypePrefix: 'slickbot:ticket:open-type:',
  TicketTypeSelect: 'slickbot:ticket:select-type',
  TicketClaim: 'slickbot:ticket:claim',
  TicketClose: 'slickbot:ticket:close',
  TicketCloseReason: 'slickbot:ticket:close-reason',
  TicketEscalate: 'slickbot:ticket:escalate',
  TicketReviewIndexFilterPrefix: 'slickbot:ticket:index-filter:',

  ReportsRefresh: 'slickbot:reports:refresh',
  ReportSetReviewChannel: 'slickbot:reports:set-review-channel',
  ReportSetPingRole: 'slickbot:reports:set-ping-role',
  ReportOpen: 'slickbot:report:open',
  ReportSelect: 'slickbot:report:select',
  ReportUserSelect: 'slickbot:report:user-select',
  ReportNoUser: 'slickbot:report:no-user',
  ReportUserModalPrefix: 'slickbot:modal:report-user:',
  ReportClaimPrefix: 'slickbot:report:claim:',
  ReportResolvePrefix: 'slickbot:report:resolve:',
  ReportDismissPrefix: 'slickbot:report:dismiss:',
  ReportDetailsPrefix: 'slickbot:report:details:',
  ReportOpenTicketPrefix: 'slickbot:report:ticket:',
  ReportReviewReasonModalPrefix: 'slickbot:modal:report-review:',
  ReportReviewIndexFilterPrefix: 'slickbot:report:index-filter:',

  ApplicationsRefresh: 'slickbot:applications:refresh',
  ApplicationSetReviewChannel: 'slickbot:applications:set-review-channel',
  ApplicationApplyPrefix: 'slickbot:application:apply:',
  ApplicationSelectPrefix: 'slickbot:application:select:',
  ApplicationApprovePrefix: 'slickbot:application:approve:',
  ApplicationDenyPrefix: 'slickbot:application:deny:',
  ApplicationReviewThreadPrefix: 'slickbot:application:thread:',
  ApplicationReviewIndexFilterPrefix: 'slickbot:application:index-filter:',

  AppealsRefresh: 'slickbot:appeals:refresh',
  AppealSetReviewChannel: 'slickbot:appeals:set-review-channel',
  AppealToggleDmDecisions: 'slickbot:appeals:toggle-dm',
  AppealOpen: 'slickbot:appeal:open',
  AppealSelect: 'slickbot:appeal:select',
  AppealApprovePrefix: 'slickbot:appeal:approve:',
  AppealDenyPrefix: 'slickbot:appeal:deny:',
  AppealApproveReasonPrefix: 'slickbot:appeal:approve-reason:',
  AppealDenyReasonPrefix: 'slickbot:appeal:deny-reason:',
  AppealReviewIndexFilterPrefix: 'slickbot:appeal:index-filter:',

  TicketModalPrefix: 'slickbot:modal:ticket:',
  TicketModal: 'slickbot:modal:ticket',
  TicketCloseReasonModal: 'slickbot:modal:ticket-close-reason',
  ReportModal: 'slickbot:modal:report',
  ReportDetailsModalPrefix: 'slickbot:modal:report-details:',
  AppealModal: 'slickbot:modal:appeal',
  AppealReasonModalPrefix: 'slickbot:modal:appeal-reason:',
  ApplicationReviewReasonModalPrefix: 'slickbot:modal:application-review:',
  ApplicationModalPrefix: 'slickbot:modal:application:',
  PanelDesignModalPrefix: 'slickbot:modal:panel-design:',
  FaqAnswerModalPrefix: 'slickbot:modal:faq-answer:',

  RolePanelSelectPrefix: 'slickbot:rolepanel-select:',

  BirthdaySetOpen: 'slickbot:birthday:set-open',
  BirthdaySavePrefix: 'slickbot:birthday:save:',
  BirthdayCancelPrefix: 'slickbot:birthday:cancel:',
  BirthdayMonthPrefix: 'slickbot:birthday:month:',
  BirthdayDayPrefix: 'slickbot:birthday:day:',
  BirthdayDayModalPrefix: 'slickbot:modal:birthday-day:',
  BirthdayTimezonePrefix: 'slickbot:birthday:timezone:',
  BirthdayTimezoneCustomPrefix: 'slickbot:birthday:timezone-custom:',
  BirthdayTimezoneModalPrefix: 'slickbot:modal:birthday-timezone:',
  BirthdayListSelect: 'slickbot:birthday:list-select',

  JoinCreateLockPrefix: 'slickbot:join-create:lock:',
  JoinCreateUnlockPrefix: 'slickbot:join-create:unlock:',
  JoinCreateClaimPrefix: 'slickbot:join-create:claim:',
  JoinCreateDeletePrefix: 'slickbot:join-create:delete:',
  JoinCreateRenamePrefix: 'slickbot:join-create:rename:',
  JoinCreateLimitPrefix: 'slickbot:join-create:limit:',
  JoinCreatePermitPrefix: 'slickbot:join-create:permit:',
  JoinCreateRemovePrefix: 'slickbot:join-create:remove:',
  JoinCreateTransferPrefix: 'slickbot:join-create:transfer:',
  JoinCreateDeleteConfirmPrefix: 'slickbot:modal:join-create-delete:',
  JoinCreateRenameModalPrefix: 'slickbot:modal:join-create-rename:',
  JoinCreateLimitModalPrefix: 'slickbot:modal:join-create-limit:',
  JoinCreatePermitModalPrefix: 'slickbot:modal:join-create-permit:',
  JoinCreateRemoveModalPrefix: 'slickbot:modal:join-create-remove:',
  JoinCreateTransferModalPrefix: 'slickbot:modal:join-create-transfer:',
  JoinCreatePermitUserSelectPrefix: 'slickbot:select:join-create-permit:',
  JoinCreateRemoveUserSelectPrefix: 'slickbot:select:join-create-remove:',
  JoinCreateTransferUserSelectPrefix: 'slickbot:select:join-create-transfer:',

  FeedsCheckNow: 'slickbot:feeds:check-now',
  FeedsRefresh: 'slickbot:feeds:refresh',
  FeedsResetConfirmPrefix: 'slickbot:feeds:reset:confirm:',
  FeedsResetCancelPrefix: 'slickbot:feeds:reset:cancel:',
  FeedsToggleAlertsPrefix: 'slickbot:feeds:toggle-alerts:',
  FeedsLiveDirectoryRefreshPrefix: 'slickbot:feeds:dir-refresh:',

  UtilityRefresh: 'slickbot:utility:refresh',
  UtilitySetupModal: 'slickbot:modal:utility-setup',
  UtilityResetConfirmPrefix: 'slickbot:utility:reset:confirm:',
  UtilityResetCancelPrefix: 'slickbot:utility:reset:cancel:',
  UtilityToggleFeaturePrefix: 'slickbot:utility:toggle:',
  UtilityEmojiPagePrefix: 'slickbot:util:emojis:page:',
  UtilityStickerPagePrefix: 'slickbot:util:stickers:page:',
  UtilityShowStickers: 'slickbot:util:show-stickers',
  UtilityShowEmojis: 'slickbot:util:show-emojis',

  PollVotePrefix: 'slickbot:poll:vote:',
  PollSelectVotePrefix: 'slickbot:select:poll-vote:',
  PollEndPrefix: 'slickbot:poll:end:',

  ReminderCancelPrefix: 'slickbot:reminder:cancel:',

  EmbedEditModalPrefix: 'slickbot:modal:embed-edit:',
  EmbedAddFieldModalPrefix: 'slickbot:modal:embed-add-field:',
  EmbedSendPrefix: 'slickbot:embed:send:',
  EmbedCancelPrefix: 'slickbot:embed:cancel:',
  EmbedEditBtnPrefix: 'slickbot:embed:edit-btn:',
  EmbedAddFieldBtnPrefix: 'slickbot:embed:add-field-btn:',

  AutoModManager: 'slickbot:automod:manager',
  AutoModRefresh: 'slickbot:automod:refresh',
  AutoModTabPrefix: 'slickbot:automod:tab:',
  AutoModToggleRulePrefix: 'slickbot:automod:toggle:',
  AutoModSetActionPrefix: 'slickbot:automod:action:',
  AutoModBlacklistAddModal: 'slickbot:modal:automod:blacklist-add',
  AutoModBlacklistRemovePrefix: 'slickbot:automod:bl-remove:',
  AutoModRaidShieldToggle: 'slickbot:automod:raid:toggle',
  AutoModRaidLockdownPromptPrefix: 'slickbot:automod:raid:prompt-lockdown:',
  AutoModRaidLockdownConfirmPrefix: 'slickbot:automod:raid:confirm-lockdown:',
  AutoModRaidDismissPrefix: 'slickbot:automod:raid:dismiss:',
  AutoModResetConfirmPrefix: 'slickbot:automod:reset:confirm:',
  AutoModResetCancelPrefix: 'slickbot:automod:reset:cancel:'
});

module.exports = { CustomIds };
