const CustomIds = Object.freeze({
  SetupRefresh: 'slickbot:setup:refresh',
  SetupModules: 'slickbot:setup:modules',
  SetupLogging: 'slickbot:setup:logging',
  SetupStatus: 'slickbot:setup:status',
  SetupTeams: 'slickbot:setup:teams',

  SetupPermissions: 'slickbot:setup:permissions',
  ResetConfirm: 'slickbot:reset:confirm',
  ResetCancel: 'slickbot:reset:cancel',
  PermissionsRefresh: 'slickbot:permissions:refresh',
  PermissionsModuleSelect: 'slickbot:permissions:module-select',
  PermissionsCommandSelect: 'slickbot:permissions:command-select',
  PermissionsTeamSelect: 'slickbot:permissions:team-select',


  HelpRefresh: 'slickbot:help:refresh',
  HelpEnabled: 'slickbot:help:enabled',
  HelpDisabled: 'slickbot:help:disabled',
  HelpEnabledSelect: 'slickbot:help:enabled-select',
  HelpDisabledSelect: 'slickbot:help:disabled-select',

  ApplicationCancelPrefix: 'slickbot:application:cancel:',
  ApplicationSubmitPrefix: 'slickbot:application:submit:',
  SetupModeration: 'slickbot:setup:moderation',
  SetupSupport: 'slickbot:setup:support',
  SetupCommunity: 'slickbot:setup:community',
  WelcomeRefresh: 'slickbot:welcome:refresh',
  RolePanelsRefresh: 'slickbot:rolepanels:refresh',
  GiveawaysRefresh: 'slickbot:giveaways:refresh',
  BirthdaysRefresh: 'slickbot:birthdays:refresh',
  ScheduledMessagesRefresh: 'slickbot:scheduled-messages:refresh',
  ServerStatsRefresh: 'slickbot:server-stats:refresh',
  LevelingRefresh: 'slickbot:leveling:refresh',
  CustomCommandsRefresh: 'slickbot:custom-commands:refresh',
  JoinCreateRefresh: 'slickbot:join-create:refresh',
  GamesRefresh: 'slickbot:games:refresh',
  GamesCounting: 'slickbot:games:counting',
  GamesTicTacToe: 'slickbot:games:tic-tac-toe',
  GamesConnectFour: 'slickbot:games:connect-four',
  FaqRefresh: 'slickbot:faq:refresh',
  SuggestionsRefresh: 'slickbot:suggestions:refresh',
  SuggestionSubmitOpen: 'slickbot:suggestions:submit-open',
  SuggestionSubmitModalPrefix: 'slickbot:modal:suggestions-submit:',
  SuggestionVoteTotalPrefix: 'slickbot:suggestions:vote-total:',
  SuggestionVoteUpPrefix: 'slickbot:suggestions:vote-up:',
  SuggestionVoteDownPrefix: 'slickbot:suggestions:vote-down:',
  GamePanelTicTacToe: 'slickbot:games:panel:tic-tac-toe',
  GamePanelConnectFour: 'slickbot:games:panel:connect-four',
  GamePanelOpponentSelectPrefix: 'slickbot:games:panel-opponent:',
  GameChallengeAcceptPrefix: 'slickbot:games:accept:',
  GameChallengeDeclinePrefix: 'slickbot:games:decline:',
  GameTicTacToeMovePrefix: 'slickbot:games:ttt:',
  GameConnectFourMovePrefix: 'slickbot:games:c4:',

  ModulesSelect: 'slickbot:modules:select',
  ModulesDetailSelect: 'slickbot:modules:detail-select',
  ModulesRefresh: 'slickbot:modules:refresh',

  LoggingRefresh: 'slickbot:logging:refresh',
  LoggingTest: 'slickbot:logging:test',

  StatusRefresh: 'slickbot:status:refresh',
  StatusActivityPlaying: 'slickbot:status:activity-playing',
  StatusActivityWatching: 'slickbot:status:activity-watching',
  StatusActivityListening: 'slickbot:status:activity-listening',
  StatusActivityCompeting: 'slickbot:status:activity-competing',
  StatusActivityStreaming: 'slickbot:status:activity-streaming',
  StatusActivityNone: 'slickbot:status:activity-none',
  StatusActivityText: 'slickbot:status:activity-text',
  StatusActivityTextModal: 'slickbot:modal:status-activity-text',
  StatusQuickOnline: 'slickbot:status:quick-online',
  StatusQuickIdle: 'slickbot:status:quick-idle',
  StatusQuickDnd: 'slickbot:status:quick-dnd',
  StatusClear: 'slickbot:status:clear',

  ModerationRefresh: 'slickbot:moderation:refresh',
  CasesRefresh: 'slickbot:cases:refresh',

  SupportRefresh: 'slickbot:support:refresh',
  SupportResetConfirmPrefix: 'slickbot:support-reset:confirm:',
  SupportResetCancelPrefix: 'slickbot:support-reset:cancel:',
  TicketsRefresh: 'slickbot:tickets:refresh',
  TicketOpen: 'slickbot:ticket:open',
  TicketOpenTypePrefix: 'slickbot:ticket:open-type:',
  TicketTypeSelect: 'slickbot:ticket:select-type',
  TicketClaim: 'slickbot:ticket:claim',
  TicketClose: 'slickbot:ticket:close',
  TicketCloseReason: 'slickbot:ticket:close-reason',
  TicketEscalate: 'slickbot:ticket:escalate',
  TicketReviewIndexFilterPrefix: 'slickbot:ticket:index-filter:',

  ReportsRefresh: 'slickbot:reports:refresh',
  ReportOpen: 'slickbot:report:open',
  ReportSelect: 'slickbot:report:select',
  ReportUserSelect: 'slickbot:report:user-select',
  ReportNoUser: 'slickbot:report:no-user',
  ReportUserModalPrefix: 'slickbot:modal:report-user:',
  ReportClaimPrefix: 'slickbot:report:claim:',
  ReportResolvePrefix: 'slickbot:report:resolve:',
  ReportDismissPrefix: 'slickbot:report:dismiss:',
  ReportDetailsPrefix: 'slickbot:report:details:',
  ReportOpenTicketPrefix: 'slickbot:report:ticket:',
  ReportReviewReasonModalPrefix: 'slickbot:modal:report-review:',
  ReportReviewIndexFilterPrefix: 'slickbot:report:index-filter:',

  ApplicationsRefresh: 'slickbot:applications:refresh',
  ApplicationApplyPrefix: 'slickbot:application:apply:',
  ApplicationSelectPrefix: 'slickbot:application:select:',
  ApplicationApprovePrefix: 'slickbot:application:approve:',
  ApplicationDenyPrefix: 'slickbot:application:deny:',
  ApplicationReviewThreadPrefix: 'slickbot:application:thread:',
  ApplicationReviewIndexFilterPrefix: 'slickbot:application:index-filter:',

  AppealsRefresh: 'slickbot:appeals:refresh',
  AppealOpen: 'slickbot:appeal:open',
  AppealSelect: 'slickbot:appeal:select',
  AppealApprovePrefix: 'slickbot:appeal:approve:',
  AppealDenyPrefix: 'slickbot:appeal:deny:',
  AppealApproveReasonPrefix: 'slickbot:appeal:approve-reason:',
  AppealDenyReasonPrefix: 'slickbot:appeal:deny-reason:',
  AppealReviewIndexFilterPrefix: 'slickbot:appeal:index-filter:',

  TicketModalPrefix: 'slickbot:modal:ticket:',
  TicketModal: 'slickbot:modal:ticket',
  TicketCloseReasonModal: 'slickbot:modal:ticket-close-reason',
  ReportModal: 'slickbot:modal:report',
  ReportDetailsModalPrefix: 'slickbot:modal:report-details:',
  AppealModal: 'slickbot:modal:appeal',
  AppealReasonModalPrefix: 'slickbot:modal:appeal-reason:',
  ApplicationReviewReasonModalPrefix: 'slickbot:modal:application-review:',
  ApplicationModalPrefix: 'slickbot:modal:application:',
  PanelDesignModalPrefix: 'slickbot:modal:panel-design:',
  FaqAnswerModalPrefix: 'slickbot:modal:faq-answer:',

  RolePanelSelectPrefix: 'slickbot:rolepanel-select:',

  BirthdaySetOpen: 'slickbot:birthday:set-open',
  BirthdaySavePrefix: 'slickbot:birthday:save:',
  BirthdayCancelPrefix: 'slickbot:birthday:cancel:',
  BirthdayMonthPrefix: 'slickbot:birthday:month:',
  BirthdayDayPrefix: 'slickbot:birthday:day:',
  BirthdayDayModalPrefix: 'slickbot:modal:birthday-day:',
  BirthdayTimezonePrefix: 'slickbot:birthday:timezone:',
  BirthdayTimezoneCustomPrefix: 'slickbot:birthday:timezone-custom:',
  BirthdayTimezoneModalPrefix: 'slickbot:modal:birthday-timezone:',
  BirthdayListSelect: 'slickbot:birthday:list-select',

  JoinCreateLockPrefix: 'slickbot:join-create:lock:',
  JoinCreateUnlockPrefix: 'slickbot:join-create:unlock:',
  JoinCreateClaimPrefix: 'slickbot:join-create:claim:',
  JoinCreateDeletePrefix: 'slickbot:join-create:delete:',
  JoinCreateRenamePrefix: 'slickbot:join-create:rename:',
  JoinCreateLimitPrefix: 'slickbot:join-create:limit:',
  JoinCreatePermitPrefix: 'slickbot:join-create:permit:',
  JoinCreateRemovePrefix: 'slickbot:join-create:remove:',
  JoinCreateTransferPrefix: 'slickbot:join-create:transfer:',
  JoinCreateDeleteConfirmPrefix: 'slickbot:modal:join-create-delete:',
  JoinCreateRenameModalPrefix: 'slickbot:modal:join-create-rename:',
  JoinCreateLimitModalPrefix: 'slickbot:modal:join-create-limit:',
  JoinCreatePermitModalPrefix: 'slickbot:modal:join-create-permit:',
  JoinCreateRemoveModalPrefix: 'slickbot:modal:join-create-remove:',
  JoinCreateTransferModalPrefix: 'slickbot:modal:join-create-transfer:',
  JoinCreatePermitUserSelectPrefix: 'slickbot:select:join-create-permit:',
  JoinCreateRemoveUserSelectPrefix: 'slickbot:select:join-create-remove:',
  JoinCreateTransferUserSelectPrefix: 'slickbot:select:join-create-transfer:'
});

module.exports = { CustomIds };
